### ISSUE TITLE
crash in macvim

### ISSUE THREAD

**Issue by lazywei** [hut/ranger#106]
Is it possible to use ranger with macvim?
I use :!ranger in macvim and get the crash
![screen shot 2013-11-10 at 12 15 09 am](https://f.cloud.github.com/assets/2840571/1506972/a63a3016-495a-11e3-88c7-5d368b7db7d9.png)

**Comment by hut** [comment]
I'm closing this because it's an old issue which has not occured in a while and is most likely resolved by now.
