### ISSUE TITLE
Tag management when moving/deleting files

### ISSUE THREAD

**Issue by mkaito** [hut/ranger#118]
Tags should be removed from the tags file when the tagged files are deleted. When moving or renaming files, they should keep their tag.

**Comment by randynobx** [comment]
Working on a patch for this.

**Comment by randynobx** [comment]
**Update on patch**

Tag management for deletes, renames, and bulk renames is implemented (but still being tested) on my personal fork of Ranger here: <https://github.com/randynobx/ranger/tree/tag_behavior_fixes>

I will submit them for inclusion in the official Ranger release once thoroughly tested and moving files has been included as well.
