### ISSUE TITLE
Dangerous <DELETE> keybind in default config.

### ISSUE THREAD

**Issue by Xender** [hut/ranger#131]
I think it's as dangerous as intuitive default - having file deletion under <delete> key is obvious, but there is a caveat:

On one common type of keyboards, <delete> and <enter> keys are separated only by a few millimeters of free space.
It's entirely possible to accidentally press both <delete> and <enter> at the same time while incautiously trying to press <enter> alone. As <delete> is currently by default bound to "console detele " which only waits for <enter>, the result is instant deletion of file instead of opening it.
And yes, it happend to me just now (fortunately the victim file wasn't important ^ ^).

I think that *all* the keybinds which pre-enter potentially-destructive commands should be in safe distance from <enter> which commits the command.

I'd suggest changing <delete> to something like <shift>-d or <shift>-<delete>.
And because current default can result in unintentional data loss, I think it's not just matter of my personal config and really the default should be changed.

Thanks for reading my suggestions
Xender

**Comment by hut** [comment]
Remapped `<DELETE>` to `dD`. And sorry for your loss :|

**Comment by Xender** [comment]
Thank you. :)

No need to be sorry.
I didn't really feel a loss, just that it wouldn't be good for it to happen to anyone anymore.

Also, it just came to me - what about also adding alternative bind like `<DELETE>d` - that is, delete key confirmed by `d`, or really any other distant key.

The point of that would be to keep the keybind intuitive (you see a one-item submenu when pressing familiar keybind) and safe at the same time.
