### ISSUE TITLE
The cursor position is lost after tabs switching

### ISSUE THREAD

**Issue by sudo-nice** [hut/ranger#157]
Stepst to reproduce:
1. Open two tabs.
2. Open a directory with a some files in the first tab.
3. Run 'search_inc' to get some file in the middle of the list.
4. Switch to the second tab ('Tab' key).
5. Switch back and see, the cursor position is lost.

My alias for 'search_inc' is 'scout -rtsfi'

ranger-master 1.6.1
Python 2.7.8

**Comment by hut** [comment]
Doesn't happen to me anymore, it probably has been fixed somewhere along the way
