### ISSUE TITLE
Compatibility with iTerm2's imgcat

### ISSUE THREAD

**Issue by JosephFerano** [hut/ranger#183]
The nightly iTerm2 build features a new script called "imgcat" that allows you to view images inside of the terminal. Instead of using w3m, this would be a great alternative since for the life of me, I can't get it to work on Mac.

Here's more info regarding the matter;

http://iterm2.com/images.html

I've tried adding it to the scope.sh file, but I can't seem to get it to work. Is there anyway it could be made to work with ranger?

**Comment by tourn** [comment]
I have no clue how he did it, but I'm using https://github.com/trishume/MacRanger and it works there.
