### ISSUE TITLE
.djvu files are recognized as images

### ISSUE THREAD

**Issue by wasamasa** [hut/ranger#201]
`rifle.conf` contains entries for `.djvu` with the appropriate viewers, however those are never considered. It looks like such files are classified as images by the highlighting and the viewers available when hitting `r`. I've looked through the sources and noticed that while `.djvu` is considered a document extension, rifle eventually ends up calling `file` just to find out the mime type of a `.djvu` file is `image/vnd.djvu` and categorizes it as image.

I've created a `~/.mime.types` file to make it consider `.djvu` files as documents. Would it make more sense for that to be a default option?

**Comment by aliulo** [comment]
Could you please write me what you have to add to  ~/.mime.types to be able to open djvu files automatically in ranger?

**Comment by wasamasa** [comment]
It contains a single line, "document/djvu djvu".

**Comment by aliulo** [comment]
This alone did not help me out. But I just figured it out, I had to change in  ~/.config/ranger/rifle.conf 
`ext djvu, has evince, X, flag f = evince -- "$@"`
to
`ext djvu, has evince,  X, flag f = djview -- "$@"`

**Comment by wasamasa** [comment]
Bump,

**Comment by hut** [comment]
I just added "application/djvu dvju" to ranger's mime.types overlay file. Not "document/..." because pdfs and other document types all use the "application/..." category. I hope this is sufficient.

**Comment by wasamasa** [comment]
I've tried locally with "application/djvu djvu" and it works as well. Thanks for fixing!
