### ISSUE TITLE
smart converter

### ISSUE THREAD

**Issue by tannhuber** [hut/ranger#208]
This is a feature request. The idea is to convert files automatically with a simple shortcut. Let's assume, you have marked a couple of `png` files. Then you press `shift`-`C`. Ranger presents a list with possible image output formats and runs an external converter (e.g. imagemagick's convert) after you have made your decision. Of course you can convert other files as well: videos, audios, raw camera images and so on.

I know, file conversion is not a simple task. In some cases you would like to apply some additional parameters. Then you must do it manually. But in all the other cases you don't need to know which tool is required and you don't need to read the manual of your conversion tool. Ranger's smart converter knows what to do.

Such an intelligent converter emedded within ranger would improve my daily work dramatically.

**Comment by hut** [comment]
Ranger has a powerful file opener already. You can add stuff like this to your ~/.config/ranger/rifle.conf to add some conversion options:
```ext png, number 21 = convert "$1" "${1%png}jpg"
ext png, number 22 = convert "$1" "${1%png}gif"```
Then press ```r``` for a list of all options, or press ```21<enter>``` on a png file to do a png->jpg conversion.

Extracting files is already built in, if you have the program "atool" installed. Just press "1<enter>" on archives.

**Comment by hut** [comment]
Comments?

**Comment by tex** [comment]
I'm fine :-)

**Comment by tannhuber** [comment]
I must apologize for forgetting this issue. I'm also fine. I think it's solved. Thank you.
