### ISSUE TITLE
different commands to open files

### ISSUE THREAD

**Issue by nkh** [hut/ranger#226]
Ranger maps "going to the right into a file" to the editor. pressing enter on a file also maps to the editor.
I often want to view the file, highlighted, before getting into the editor. I would prefer to have different command. going into the file -> pager, 'return' -> edit.

while in the pager, if highlight is used, it would be good to be able to open it in the editor with a key press, like 'less' does.

**Comment by randynobx** [comment]
There is alread a command like this. If you hit <code>i</code> while a file is selected, it will bring up a pager full screen.

You can then exit by hitting <code>i</code> again, and then quickly edit by hitting <code>enter</code> or <code>l</code>.

Here is an excerpt from the ranger <code>man page</code>

            i             Display the current file in a bigger window.
