### ISSUE TITLE
Any plan for new release?

### ISSUE THREAD

**Issue by junegunn** [hut/ranger#229]
Hi, first of all, thanks for Ranger. It's great.
I use OS X and installed Ranger using Homebrew, and realized that `:bulkrename` does not work as expected but a quick search showed me that the problem was [already fixed](https://github.com/hut/ranger/issues/136). So I tried to upgrade ranger using homebrew, only to find out I was already using the most recent stable release, 1.6.1 which was released in 2013. Do you have any plan to release a new version?

**Comment by taylorchu** [comment]
I am also waiting for a new release.

**Comment by hut** [comment]
Yes, I've been putting it off because it requires quite some effort for testing, adding compatibility code, etc. which I could instead invest into implementing new features or fixing bugs.

But I guess it can't be avoided in the long run. I'll see to it soon.
