### ISSUE TITLE
Mouse click should not have any effect if the click is setting focus on the window

### ISSUE THREAD

**Issue by nkh** [hut/ranger#231]
Clicking on an unselected window with ranger running, selects the window and also generates a click event. Vry disturbing when things start opening in gimp, the browser and vi when one wants only to set the focus on ranger's window.

**Comment by hut** [comment]
So what's wrong with `set mouse_enabled off`

**Comment by nkh** [comment]
I don't want to remove mouse support, I want mouse support to not generate an action ven when the event is focusing the window

**Comment by hut** [comment]
I don't see how that's possible from within ranger. You'll need to configure your window manager for that.
