### ISSUE TITLE
One console/editor per tab

### ISSUE THREAD

**Issue by nkh** [hut/ranger#232]
when using multiple tabs, if a file is edited, all commands go to the program editing and thus moving from tab to tab is not possile. 

This is something between a window manager and a file manager but it seems to be my work flow. 

binding a command to open the file in a different window doesn't flow well. I run ranger in a tmux pane and there is no way, afaik, to do it in tmux

**Comment by hut** [comment]
You want ranger to spawn a vim instance inside a tab, replacing the directory listing with vim, so you can edit without losing the ability to switch tabs and browse around in other directories?

**Comment by nkh** [comment]
yes

**Comment by nkh** [comment]
yes

**Comment by hut** [comment]
I don't see this happening, I'm sorry.
