### ISSUE TITLE
Improving robustness of :mkdir...

### ISSUE THREAD

**Issue by aksr** [hut/ranger#238]
It would be nice if *:mkdir* command would be more robust. 
Adding possibility to create multiple levels directories like this:
*:mkdir dir/{dir1,dir2,dir3}*
or 
*:mkdir dir/{dir1/{1,2},dir2,dir3}*
Also if you want directory name containing **{**, it could be escaped: **\\{**

**Comment by randynobx** [comment]
It should be easy to make *:mkdir* create intermediate directories (like mkdir -p /path/to/newdir in BASH) by simply changing os.mkdir() to os.mkdirs() at line 1293 in core/actions.py:

_Current_
```python
    def mkdir(self, name):
    try:
        os.mkdir(os.path.join(self.thisdir.path, name))
    except OSError as err:
        self.notify(err)
```
_Allows for a chain of new directories_
```python
    def mkdir(self, name):
    try:
        os.mkdirs(os.path.join(self.thisdir.path, name))
    except OSError as err:
        self.notify(err)
```

*Note: I haven't implemented and tested this yet, it is just a quick idea of how we could make :mkdir a bit more robust*

As for creating multiple directories in parallel (as opposed to a string as the above would allow), we might need to add handling of { and } and parse through them with multiple os.mkdir(s) calls.

I'll take a deeper look into it and see if I can implement this functionality.

**Comment by hut** [comment]
Odd, I thought we had mkdirs already. I'll go ahead and patch it.

**Comment by randynobx** [comment]
Awesome! I'll continue looking into the brace/bracket expansion functionality. I have some code fleshed out now that might work, still a lot of testing I need to do before it goes anywhere though. Its a bit messy, and will likely get more so before I get it to work; so it will probably have to be a bigger concerted effort than a simple function edit.

Although, brace expansion probably would be better suited as a feature/helper function outside of just mkdir if it ever is implemented.

@hut Would you think the brace expansion is worth looking into?

**Comment by hut** [comment]
I really don't see why you wouldn't just `:alias mkdir shell mkdir -p`

**Comment by randynobx** [comment]
Wow, it's been so long since I used :alias that I completely forgot about it. Thanks for the tip

**Comment by hut** [comment]
@aksr: would `:alias mkdir shell mkdir -p` suit all your needs?

**Comment by aksr** [comment]
@hut: Yes.
