### ISSUE TITLE
Error when previewing available themes

### ISSUE THREAD

**Issue by vimeitor** [hut/ranger#244]
Hello,

Going into command mode, writing "set colorscheme " and pressing tab shows me the following error:
```
<ranger.colorschemes.default.Default object at 0x7fc9db250470>
```
I can reproduce this even when running in clean mode. Can you reproduce it or it's just me?

Thank you!

**Comment by hut** [comment]
It's just the internal representation of the default colorscheme. So it's not an error but a bug, since the tab completion on this setting is useless.

**Comment by vimeitor** [comment]
Oh, I see. Sorry about that. I thought the expected behavior was ranger alternating between all the available options.

**Comment by hut** [comment]
Well, it's justified to leave this open since the tab completion is genuinely broken. It should expand to `set colorscheme default`.
