### ISSUE TITLE
Cached python should not be stored in .config

### ISSUE THREAD

**Issue by mightyCelu** [hut/ranger#248]
I just recognized that the commands.py is compiled in my .config/ranger directory. This will create a __pycache__ directory which I think should rather be placed in .cache/ranger.
This can be bad for users who keep their configuration in a version control system who then have to ignore this directory.
The same argument might be made for the history and bookmarks files (maybe).

**Comment by arwer13** [comment]
+1

**Comment by hut** [comment]
I disabled creating cached files entirely because they cause quite the confusion in general.
I'll consider moving the history/bookmarks/tags to another place. Thanks for your input <3
