### ISSUE TITLE
/usr/bin/python vs /usr/bin/env python

### ISSUE THREAD

**Issue by kwkelly** [hut/ranger#250]
The first line in ranger.py reads '#!/usr/bin/python -O', but using '!#q/usr/bin/env python' increases portability for those with different python install locations. I had to make this change in order to get ranger to run.

However, then it's not possible to portably pass the -O optimization flag to python.

Is there a fix that satisfies both?

**Comment by hut** [comment]
If you run `make install`, it will set the proper shebang line automatically. Is that good enough?

**Comment by kwkelly** [comment]
Ohh I was just running the script directly.

This can be closed then I think.
