### ISSUE TITLE
the option named vcs_aware does not exist

### ISSUE THREAD

**Issue by leebrooks0** [hut/ranger#258]
This file browser is amazing!

I am trying to get some git integration going, so I go ```:set vcs_aware true```,
but I keep getting this error: ```the option named vcs_aware does not exist```

Am I doing something wrong?

**Comment by hut** [comment]
Perhaps you have an old version. Try the most recent version from git.

**Comment by leebrooks0** [comment]
Yeah, I got it via apt, so...
also i installed highlight and no syntax highlight etc. so i will try out the latest version later today...

**Comment by leebrooks0** [comment]
Correct, once I installed from source I have the option. Thanks!
