### ISSUE TITLE
Hidden files and the selection broken

### ISSUE THREAD

**Issue by Vifon** [hut/ranger#259]
**Steps to reproduce**

1. Create an empty directory, e.g. `topdir`.
2. Create a hidden directory inside of it, e.g. `.hidden` and create a file inside of it.
3. Navigate with ranger to `topdir`.
4. Show the hidden files with `zh`.
5. Try to enter `.hidden` with `l`.

**What happens**

The `.hidden` directory is not selected despite being highlighted: I cannot enter it and there is no preview. If I press `j` to go to the next file (even though there is no next file), `.hidden` becomes truly selected but then hiding the hidden files again does not deselect it, even if I try changing the directories.

**What was expected**

Showing and hiding the hidden files should modify the current selection if needed.

**Comment by randynobx** [comment]
I've reproduced this bug with the following setup:

OS: Arch Linux
Python Version: 3.4.3
Ranger Release: 1.6.1

**Comment by randynobx** [comment]
To add to the above notes of the bug:

When in <code>topdir</code>, with <code>.hidden</code> not selected, if you create a new non-hidden directory <code>lowdir</code>, everything works as expected; ie. the <code>.hidden</code> directory is instantly selected (assuming sort has hidden folders appear at top of list) and general behavior is as expected when dealing with directories in ranger.

**Comment by dufferzafar** [comment]
@hut @Vifon Since #329 has been merged. I think you can now close this issue.

**Comment by Vifon** [comment]
Right, it seems to work now, thanks.
