### ISSUE TITLE
Custom image previews ignoring the "preview_images" option

### ISSUE THREAD

**Issue by Vifon** [hut/ranger#263]
The custom images previews (these using the `$cached` env variable) are completely ignoring the `preview_images` option. In my opinion they should be affected by it just like the regular image previews.

**Solution 1**: Just don't display the generated image when `preview_images` is disabled. **Problem**: `scope.sh` would not be able to fall back to a textual preview.

**Solution 2**: Set `$cached` only when `preview_images` is `true` and then `scope.sh` would branch on `[ -n "$cached" ]`. **Problem**: the backward compatibility. The existing `scope.sh`s using this feature would need to consider the possibility of `$cached` being empty. It would break the existing configs.

**Solution 3**: Add an another variable to indicate whether an image should be generated and ignore the image if it still is created. It would work like the previous solution but would not break the existing configs.

**Comment by hut** [comment]
fixed in #372
