### ISSUE TITLE
my bookmarks stopped being saved

### ISSUE THREAD

**Issue by tkossak** [hut/ranger#267]
I created some bookmarks with ```m``` key, and they work as they should, but now when i create new bookmark and restart ranger the bookmark is not saved: when i press apostrophe i don't see it on the list and it is not present in the file ```~/.config/ranger/bookmarks``` (i have rw permissions to the file).

Some options in ```~/.config/ranger/rc.conf```:
>    set show_hidden_bookmarks true
>    set autosave_bookmarks true

Please help, thank you.

**Comment by hut** [comment]
does it happen with 1 particular directory, or everywhere?

**Comment by tkossak** [comment]
ok i fixed it - it was my fault, the owner of the ```~./config/ranger/bookmarks``` was root instead of me. Don't know how it happened but I changing the owner to me and it works again.
