### ISSUE TITLE
vim error

### ISSUE THREAD

**Issue by lidaling** [hut/ranger#277]
There are errors when I open txt file in ranger console.
How to fix it ?
Thank you.

```
Error detected while processing /home/lidl/.vimrc:
line    3:
E319: Sorry, the command is not available in this version: let g:molokai_original = 1
line    4:
E319: Sorry, the command is not available in this version: execute pathogen#infect()
Press ENTER or type command to continue
```

**Comment by hut** [comment]
Have you read the error message?

**Comment by lidaling** [comment]
But using vim in terminal ,all is ok. Why.

**Comment by lidaling** [comment]
How to change the ranger's vim version?

**Comment by Vifon** [comment]
Check if the same error appears when you run Vim as `vi`, `vim.basic`, `vim.tiny` or something like that. If so, set your `$EDITOR` variable to the proper version of Vim and that should be it.

**Comment by hut** [comment]
I wonder, is this still a problem?

**Comment by lucideer** [comment]
I'm seeing this same error launching text files from ranger.

 - `vi`, `vim` and `vim.basic` all work fine.
 - `vim.tiny` gives me the same `.vimrc`-related error messages that I see in ranger.
 - **$EDITOR** is undefined

I would assume, looking at the rifle source, that it should default to running `vim` if **$EDITOR** isn't set, but for some reason it seems it's running `vim.tiny` instead?

**Comment by lucideer** [comment]
**Update:** I'm on a Debian distro and it seems that rifle was defaulting to calling `/usr/bin/sensible-editor` from the `sensible-utils` package. Running `select-editor` fixed the problem.
