### ISSUE TITLE
Can't run ranger from Neovim

### ISSUE THREAD

**Issue by schrislambert** [hut/ranger#279]
Sorry if I'm in the wrong place, I don't know on whose side of the fence this is on.

When running `:!ranger` from Neovim, you get an error saying:
```
Error: Must run ranger from terminal
shell returned 1

Press ENTER or type command to continue
```

This breaks the vim_file_chooser.vim file in the examples folder.

**Comment by hut** [comment]
In vim, if you use `:!somecommand`, the currently selected text is piped through `somecommand` and replaced by its output. This is something else than simply "running somecommand".
From the error message, I gather neovim behaves similar, because that message also occurs if you run e.g. `echo hello | ranger`. I suggest you research the way to plainly start a command without messing with its input/output streams.

**Comment by schrislambert** [comment]
I search a bit further and found that Neovim isn't able to run interactive programs with `!:` yet, and issues has been opened in neovim at neovim/neovim#1496, and, in fzf at junegunn/fzf#137.

**Comment by bramblex** [comment]
@hut 
@schrislambert 

I always using ranger like this, in vim.
```VimL
function! s:ChooseFile(dir_path)
    let tmp_file = tempname()
    let path = s:AbsolutePath(a:dir_path)

    silent exec join(['!ranger', path, '--choosefile=' . tmp_file], ' ')
    redraw!

    let result = 0
    if filereadable(tmp_file)
        silent let result = system('cat '. tmp_file)
    endif
    silent call system('rm -rf ' . tmp_file)
    return result
endfunction
```

Now I can run ranger but can not get the result. Is there any callback function can be used with `:teram` ?

**Comment by francoiscabrol** [comment]
Hi I found a way to use it from the fzf.vim implementation:
 function! OpenRanger()
    let rangerCallback = { 'name': 'ranger' }
    function! rangerCallback.on_exit(id, code)
      try
        if filereadable('/tmp/chosenfile')
            exec 'edit ' . readfile('/tmp/chosenfile')[0]
            call system('rm /tmp/chosenfile')
        endif
      endtry
    endfunction
    enew
    call termopen('ranger --choosefile=/tmp/chosenfile', rangerCallback)
    startinsert
  endfunction

I have created a plugin that works with vim and neovim: https://github.com/francoiscabrol/ranger.vim

**Comment by bramblex** [comment]
Thanks a lot!

**Comment by introom** [comment]
is it possible to run ranger inside a terminal emacs ?

(call-process "/usr/bin/ranger") doesn't make it.

On the other hand, M-! "/usr/bin/ranger" outputs: Error: Must run ranger from terminal
