### ISSUE TITLE
Recursive search for files/folders and display inside ranger?

### ISSUE THREAD

**Issue by phongvcao** [hut/ranger#288]
I just wonder how can I do a recursive search for a file/folder with title "TitleX" or pattern ".*TitleX$", for example, in the current directory and all of its subdirectories (like in Nautilus, Midnight Commander, etc.) and display it somewhere inside ranger? I use this feature a lot and believe many people do, and thus I just want to ask for a way to do it in ranger. In case this feature is not built-in into ranger, I suggest that it should be in the next ranger's releases because it is such a crucial feature of a file manager to have.

**Comment by tex** [comment]
I miss this feature too. Poor man's solution is to use :flat -1 and then search the result. Not the fastest method though.

**Comment by GermainZ** [comment]
You should be able to chain flat and filter to achieve this. For example: `map F console chain flat -1; filter `

**Comment by phongvcao** [comment]
@GermainZ you suggestion doesn't work for my case. I just tried it out...

**Comment by randynobx** [comment]
@phongvcao 
Please note that <code>:flat</code> is only available in the git version of ranger at this time. If you are using v1.6.1 or earlier, the flat command will not work.

**Comment by GermainZ** [comment]
@phongvcao probably because you're running 1.6.1 with doesn't have `flat` (same reason tex's suggestion fails -- both our suggestions make use of `flat`). You can try upgrading to the latest version if you want.

**Comment by phongvcao** [comment]
@GermainZ @randynobx if this recursive search feature is present in the next releases of ranger (using flat) then I think this issue is resolved. I can wait until the development release make it to stable.

**Comment by pedrols** [comment]
There's a workaround using FZF https://github.com/gotbletu/shownotes/blob/master/ranger_file_locate_fzf.md 

It doesn't work with non ASCII characters though
