### ISSUE TITLE
[Error] Ranger closes immediately when invoking with gnome-terminal command

### ISSUE THREAD

**Issue by phongvcao** [hut/ranger#289]
I am trying to bind some shortcut keys to start gnome-terminal and Ranger straight instead of first opening the shell and then issuing "ranger". However, when I invoke the command:

```bash
gnome-terminal -e "ranger"
```

a new gnome-terminal window is opened and it said "loading ranger" and then closes immediately after 1-2 seconds. Does anyone know how to invoke Ranger straight this way instead of having to first fire-up the terminal and issuing the command "ranger", or is this feature not supported by Ranger?

**Comment by randynobx** [comment]
I have a keybinding setup to do this, and have successfully tested it with urxvt, sakura, and gnome-terminal.

Could you elaborate on your setup? ie OS, Python version, ranger version, etc

**Comment by phongvcao** [comment]
Here is my setup:

OS: Arch Linux x86_64
Python 3.4.3
Ranger 1.6.1 (Stable)

**Comment by hut** [comment]
Try something like `gnome-terminal -e sh -c 'ranger; sleep 10'` and look out for error messages

**Comment by phongvcao** [comment]
@hut Here is what I got by running ```gnome-terminal -e "sh -c 'ranger; sleep 10'"```

```
ranger version: 1.6.1, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 8, in inner_cached_function
    return cache[args]
KeyError: (<colorschemes.solarized.Solarized object at 0x7fe0d8a11128>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 133, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 310, in loop
    ui.redraw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 262, in redraw
    self.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 288, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 150, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 53, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python3.4/site-packages/ranger/gui/colorscheme.py", line 67, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 26, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

ranger crashed.  Please report this traceback at:
http://savannah.nongnu.org/bugs/?group=ranger&func=additem
```

**Comment by randynobx** [comment]
But ranger is starting fine if you open the terminal, and then run ranger? It looks like the issue could be something with the solarized colorscheme.

Could you try changing the color scheme back to default or another scheme and seeing if the issue still occurs?

**Comment by phongvcao** [comment]
@randynobx Yeah you are correct. The problem is in the solarized.py colorscheme. After I switched back to the "default" colorscheme, everything works fine. I think this issue is related to Issue #68 which requires me to:

```
set -g default-terminal "screen-256color"
```

in my .tmux.conf file. However, when firing up ``` gnome-terminal -e "ranger" ```, gnome-terminal doesn't run Tmux and thus the default-terminal is not set to "screen-256color" (solarized.py takes advantage of 256color mode of the terminal).

**Comment by phongvcao** [comment]
@hut @randynobx Okay guys so finally I have found a solution for this. In order to launch ranger using gnome-terminal -e, all I have to do is to use this command:

```bash
gnome-terminal -e "sh -c 'export TERM="screen-256color"; ranger'"
```

I also made an alias in my bashrc for this:

```bash
alias ranger="gnome-terminal -e "sh -c 'export TERM="screen-256color"; ranger'"
```

I believe there is no other way to fix the issue and the issue is not the fault of solarized.py itself but rather the fact that Solarized takes advantage of the 256color mode in gnome-terminal.

If possible, please update the Ranger Documentation about this issue so other users can be aware of it. 

Thank you guys!
