### ISSUE TITLE
Starting fish shell with `:shell $SHELL`

### ISSUE THREAD

**Issue by iamevn** [hut/ranger#300]
After updating from v1.6.1 to v 1.7.0, I can no longer start a shell from within ranger by pressing S.
Fish tries to start and immediately returns with the error message:

    fish: Variables may not be used as commands. Instead, define a function like 'function SHELL; /usr/bin/fish $argv; end' or use the eval builtin instead, like 'eval $SHELL'. See the help section for the function command by typing 'help function'.
    Standard input: $SHELL

**Comment by hut** [comment]
This was introduced in #187, and it happens because apparently fish forbids something like `env SHELL=fish fish -c "$SHELL"` whereas it works for any other shell I tested. Oh well. Fixed.

**Comment by iamevn** [comment]
I'm actually still getting this error on 1.7.1
```
fish: Variables may not be used as commands. Instead, define a function like 'function SHELL; /usr/bin/fish $argv; end' or use the eval builtin instead, like 'eval $SHELL'. See the help section for the function command by typing 'help function'.
Standard input: $SHELL
                ^
evan@archpad ~> ranger --version
ranger-master 1.7.1

Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)]
```
