### ISSUE TITLE
w3m image previews broken

### ISSUE THREAD

**Issue by hut** [hut/ranger#301]
the update of w3m from 0.5.3-5 => 0.5.3-6 (on Arch) has broken the w3m image previews

**Comment by AnderRasoVazquez** [comment]
I can confirm this bug.

**Comment by archeando** [comment]
I have the same problem, the preview not work with w3m.

**Comment by randynobx** [comment]
This is an issue with w3mimg and not ranger. 
The changelog for the update: https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/w3m&id=236a5ad10a1614c4079235fd4b437199798dc1dc

**Comment by tex** [comment]
The same problem here.

**Comment by randynobx** [comment]
Issue has been reopened for w3m regarding this issue: https://bugs.archlinux.org/task/44613

**Comment by spaceporn** [comment]
Same problem here too. If needed, I can provide information to help fix this issue.

**Comment by tecnopado** [comment]
if can help this image show the output error http://i.imgur.com/KeCOHFm.png

**Comment by tecnopado** [comment]
situation update..  now i can see the preview of the images in ranger.. but NOT in w3m ! O_o  
http://imgur.com/XO2ZNUO  the preview disappear only when "my" script change wallpaper ...  i don't know why.. and i don't know why now the images working in ranger.. and NOT in w3m ... strange!

**Comment by randynobx** [comment]
Update: Issue has been fixed in w3m 0.5.3-7

Update available in pacman now.
