### ISSUE TITLE
Add space before path in titlebar?

### ISSUE THREAD

**Issue by eMPee584** [hut/ranger#304]
Most terminal programs do not handle ':' as word separator, so double-clicking the path will select the full line, including the prefixed `user@hostname:` . This is inconvenient for copy/pasting paths. Inserting whitespace after the colon fixes that. Is that an acceptable default?

    -        bar.add(':', 'hostname', clr, fixed=True)
    +        bar.add(': ', 'hostname', clr, fixed=True)

**Comment by hut** [comment]
Some printf-like string, definable through an option, with which you could customize the way the titlebar looks like, would be pretty badass.

**Comment by eMPee584** [comment]
Until then, a simple space for us who like shift-double-clicking the file path to grab into the x-selection already would be amazing :grinning:

**Comment by hut** [comment]
Yes, you are right. =P
