### ISSUE TITLE
crash at startup with "set colorscheme solarized"

### ISSUE THREAD

**Issue by jhxie** [hut/ranger#307]
Hi, currently I am running ranger(installed from pacman community/ranger) on the most up to date version of archlinux, but it will crash if I put "set colorscheme solarized" configuration into the rc.conf($HOME/.config/ranger/rc.conf) after I use "ranger --copy-config=all"; the other 3 colorschemes seem to work fine(default, jungle, snow).

Version info returned with "--version" flag:
> ranger-stable 1.7.0
> Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
> [GCC 4.9.2 20150304 (prerelease)]

Below are the full traceback:
> ranger version: 1.7.0, executed with python 3.4.3
> Locale: en_CA.UTF-8
> Current file: /home/jiahui/book
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 8, in inner_cached_function
>     return cache[args]
> KeyError: (<ranger.colorschemes.solarized.Solarized object at 0x7ff6dc58b208>, 'in_titlebar', 'hostname', 'good')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 29, in get_color
>     curses.init_pair(size, fg, bg)
> _curses.error: init_pair() returned ERR
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
>     fm.loop()
>   File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
>     ui.redraw()
>   File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
>     self.draw()
>   File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
>     DisplayableContainer.draw(self)
>   File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
>     displayable.draw()
>   File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
>     self._print_result(self.result)
>   File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
>     self.color(*part.lst)
>   File "/usr/lib/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 57, in color
>     attr = self.settings.colorscheme.get_attr(*keys)
>   File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
>     value = fnc(*args)
>   File "/usr/lib/python3.4/site-packages/ranger/gui/colorscheme.py", line 66, in get_attr
>     return attr | color_pair(get_color(fg, bg))
>   File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 38, in get_color
>     curses.init_pair(size, fg, bg)
> _curses.error: init_pair() returned ERR
> 

Thank you for addressing this issue.

**Comment by jhxie** [comment]
Solved with
`alias ranger='TERM=xterm-256color ranger'`

**Comment by pesterhazy** [comment]
I'm also seeing this bug (on NixOS) with the solarized theme. @jhxie's workaround works. My usual TERM=xterm

**Comment by hut** [comment]
fixed in 2aa3b9dd82b64e79a3d4027727afbbb881ccb3b3
