### ISSUE TITLE
bulkrename with python 3.4.3 (arch linux)

### ISSUE THREAD

**Issue by hnsn1** [hut/ranger#308]
i'm getting this errormessage when i try to use the :bulkrename command:
sequence item 0: expected str instance, bytes found
i'm getting the message when i finished editing the file with the filenames and saves it. I'm getting trown out to ranger with the errormessage visable for a few seconds.

i havent used the bulkrename command for a while, maybe my python version have been upgraded since last time

**Comment by randynobx** [comment]
This issue was already reported in #299 and subsequently fixed in commit 11920818c6bd43e9c7fb2e654dff25650038c083

The bug was introduced in the 1.7.0 version update, but has since been fixed in the git master branch.
