### ISSUE TITLE
Renaming folders doesn’t work.

### ISSUE THREAD

**Issue by Profpatsch** [hut/ranger#311]
I hit `I`, type the name changes, hit `Return` and get the error:

    No module named 'ranger.fsobject'

Archlinux, current version [1.7.0](https://www.archlinux.org/packages/community/any/ranger/).

**Comment by hut** [comment]
Updating your ~/.config/ranger/commands.py (e.g. by deleting it and getting a fresh one with `ranger --copy-config=commands`) should fix this.

**Comment by Profpatsch** [comment]
Not sure why there is lots of program code in my configuration, but ok.

**Comment by hut** [comment]
Yeah, sorry about that. It was like that for easier customization. Newer versions deal more cleanly with it by supplying a bare-bone commands.py file so you can upgrade more easily.

**Comment by Profpatsch** [comment]
I see, that’s good.
