### ISSUE TITLE
Is it possible to turn off keychain pop-up window

### ISSUE THREAD

**Issue by A1phaZer0** [hut/ranger#319]
Hi,
Is there a way to turn off command prompt? The prompt window always pops up when I press some key like 'g'. No description for that on man pages.

Many thx.

**Comment by hut** [comment]
Sure, you need to create the file ~/.config/ranger/plugins/hide_key_hints.py and put in this code:
```py
from ranger.gui.widgets.browserview import BrowserView
BrowserView._draw_hints = lambda self: None
```

**Comment by A1phaZer0** [comment]
Fantastic! Thx!
