### ISSUE TITLE
"bzip2: I/O or other error" when displaying help under python 2

### ISSUE THREAD

**Issue by hsoft** [hut/ranger#325]
Source: https://bugs.gentoo.org/show_bug.cgi?id=409745

Steps to Reproduce:
1. Run ranger under python 2
2. Press '?' to open man page
3. Quit man page
4. Quit ranger

Result:

```
bzip2: I/O or other error, bailing out.  Possible reason follows.
bzip2: Broken pipe
	Input file = /usr/share/man/man1/ranger.1.bz2, output file = (stdout)

bzip2: I/O or other error, bailing out.  Possible reason follows.
bzip2: Broken pipe
	Input file = /usr/share/man/man1/ranger.1.bz2, output file = (stdout)
```

**Comment by hsoft** [comment]
To be sure, I also verified that the bug happens when building directly from the repo, not only from gentoo packages.

**Comment by hut** [comment]
Can't reproduce on archlinux. Perhaps because of
```
$ find /usr/share/man/ -name 'ranger*'
/usr/share/man/man1/ranger.1
/usr/share/man/man1/ranger.1.gz
```

> To be sure, I also verified that the bug happens when building directly from the repo, not only from gentoo packages.

That's odd, because ranger's install script doesn't compress the man page.

**Comment by hsoft** [comment]
I don't think it's related to how the man page was installed. Even though I was running directly from the repo, the `/usr/share/man/man1/ranger.1.bz2` file in question was the one that I had already installed from Portage.

The interesting part is that it only happens with python 2. It probably is something about `Popen` that changed between 2 and 3.

**Comment by hut** [comment]
Does it happen with this too?
```py
python -c 'from subprocess import *; Popen(["man", "ranger"]).wait()'
```

**Comment by hsoft** [comment]
Yes, but not with `python3 -c 'from subprocess import *; Popen(["man", "ranger"]).wait()'`. It doesn't do that an your system? So it would be an env-specific bug?

**Comment by hut** [comment]
Yup, works for me. With both pyhon 2.7.10 and 3.4.3.

**Comment by hsoft** [comment]
Oh, then this problem would be entirely unrelated to ranger. Sorry for the noise.
