### ISSUE TITLE
Completion in command line

### ISSUE THREAD

**Issue by nkh** [hut/ranger#331]
ranger neither shows the possible completions (probably due to a single line available) nor does it cycle through possible completions.

IE: ":list-<t<b>" doe nothing useful

learning curve would be reduces if a completion existed.

**Comment by hut** [comment]
Actually, yes it does. Try `:a<TAB>`, it'll cycle through `:a`, `:abort` and `:alias`.

**Comment by nkh** [comment]
Lol! 

yes it does. the lol is that I reported a ranger problem on tmux channel yesterday and I report a tmux problem on ranger today. I need more sleep.

:)

**Comment by hut** [comment]
Right, this is an issue in tmux =D I hope it gets fixed too.
