### ISSUE TITLE
scope.sh -E causes issues on OS X

### ISSUE THREAD

**Issue by dan-c-underwood** [hut/ranger#344]
The `-E` flag that follows `/bin/echo` on lines 31 and 39 in the default **scope.sh** causes:

* `-E`to be output at the start of every previewed text file
* Previews of PDFs, archives and HTML pages to not appear

Removing the `-E` prevents the two above issues (but not sure if that has knock-on effects?) - it seems like it considers the `-E` as part of the echo input rather than a flag for it.

Platform: OS X Yosemite (10.10.4)
Terminal: Terminal.app and iTerm2
Shell: zsh

**Comment by ptzz** [comment]
`echo` behaves a bit strange on Mac. Using `-E` gives different results with `echo` vs `/bin/echo`.

```
~$ echo -E "fo\o"
fo\o
~$ /bin/echo -E "fo\o"
-E fo\o
~$ which echo
/bin/echo
~$ type echo
echo is a shell builtin
~$
```
