### ISSUE TITLE
Copies/moves files LIFO/stack-style

### ISSUE THREAD

**Issue by zaz** [hut/ranger#345]
If you start copying a second file in Ranger before a previous file has finished copying, that operation is paused while the newest file is copied. Obviously a queue would be more desirable here, as the current method creates a lot of partial files.

#### Steps to reproduce:

0. Plug in a flash-drive with a few large files on it (or a slow flash-drive with normal files)
1. Watch the destination directory in another window, e.g. `watch -n .2 ls -l ~`
2. Use <kbd>yy</kbd>, <kbd>gh</kbd>, <kbd>pp</kbd> to copy the first file onto your computer
3. Quickly copy the others in the same fashion
4. Observe that you now have several partial files. The *last* file you pasted is actively copying. When that finishes, the second-last, and so on.

**Comment by lamarpavel** [comment]
>Obviously a queue would be more desirable here

Not so obvious to me, as there are benefits to the LIFO-style. One such situation would be when you first copy one large file - where the operation takes an hour to complete - and then copy a small file, that you need copied asap. With a FIFO you would wait an hour until the second file, a 2kb-sized conf-file, is copied.

Whether a FIFO or LIFO is to be preferred depends on the situation. As such the user should have the option to chose between the two or modify the stack/queue after adding files to it.

**Comment by zaz** [comment]
@lamarpavel: Good point. I suppose others might actually want LIFO. How about copying files smallest-first-out? Size being determined by how much is *left* to copy? Would that be hard to implement?

I'm not a very experienced programmer, but if someone could give me a pointer to where in the code this needs to be changed, I could have a go at doing it.

**Comment by lamarpavel** [comment]
I think a better approach might be to have two different paste-actions, one for adding the copy/move operation to each end of the job queue. Possibly ```pp``` and ```pP```.

Additionally it would be cool to be able to modify the job queue afterwards, but I think there was an issue for that already - which I can't find right now.

**Comment by tex** [comment]
+1

**Comment by hut** [comment]
Good idea @zaz and thanks @lamarpavel for the input. I pushed a fix that does it as you suggested, adding the key bindings `pP` and `pO`

**Comment by zaz** [comment]
Cool. Thanks!
