### ISSUE TITLE
Provide .desktop file

### ISSUE THREAD

**Issue by mightyCelu** [hut/ranger#346]
it would be great if ranger provided a desktop file. With this it would be possible to 
* start ranger directly from application launchers like krunner without starting a terminal first
* have ranger integrated in "open with filemanager" dialogs

This is the .desktop file I currently use:
```
[Desktop Entry]
Type=Application
Name=ranger
Comment=Launches the ranger file manager
Icon=utilities-terminal
Terminal=true
Exec=ranger
Categories=ConsoleOnly;System;FileTools;FileManager
MimeType=inode/directory;inode/mount-point;x-scheme-handler/ssh;x-scheme-handler/smb;x-scheme-handler/nfs;x-scheme-handler/ftp;
```

**Comment by hut** [comment]
I don't know anything about `.desktop` files. Can I just steal yours?

**Comment by mightyCelu** [comment]
Of course you can. It works for me but it might contain some errors.

**Comment by spelufo** [comment]
Check to see if your umask doesn't change to 000. I have this problem after doing `xdg-mime default ranger.desktop inode/directory`. I already had the same issue trying to set a gnome-terminal.desktop as the default way to open directories, to use is instead of a file browser. I'm looking for a solution.

**Comment by mightyCelu** [comment]
My umask is still at 022. However I didn't use xdg-mime explicitly, I set in the KDE Plasma settings. `xdg-mime query default inode/directory` returns ranger.desktop.

**Comment by teto** [comment]
Thanks for this !
You can install it with:
xdg-desktop-menu install --novendor ranger.desktop

**Comment by hut** [comment]
Done. "./setup.py install" now installs it. However, only when you don't have python's setuptools module. It works with the old distutils though, which is a fallback if you don't have setuptools. Gotta figure out what to do about setuptools.
