### ISSUE TITLE
small patch to loader.py

### ISSUE THREAD

**Issue by notEvil** [hut/ranger#352]
Hi,

I have a few commands which need to set Popens cwd to work properly. This patch just adds the possibility to do that. Would you mind adding this to the main branch?

    --- loader.py	2015-08-02 09:43:55.162867333 +0200
    +++ loader.py.new	2015-08-02 09:18:20.982172455 +0200
    @@ -130,7 +130,7 @@
         finished = False
         process = None
         def __init__(self, args, descr, silent=False, read=False, input=None,
    -            kill_on_pause=False):
    +            kill_on_pause=False, popenArgs=None):
             SignalDispatcher.__init__(self)
             Loadable.__init__(self, self.generate(), descr)
             self.args = args
    @@ -139,6 +139,7 @@
             self.stdout_buffer = ""
             self.input = input
             self.kill_on_pause = kill_on_pause
    +        self.popenArgs = popenArgs
     
         def generate(self):
             py3 = sys.version_info[0] >= 3
    @@ -146,8 +147,10 @@
                 stdin = PIPE
             else:
                 stdin = open(os.devnull, 'r')
    -        self.process = process = Popen(self.args,
    -                stdout=PIPE, stderr=PIPE, stdin=stdin)
    +        popenArgs = {} if self.popenArgs is None else self.popenArgs
    +        popenArgs['stdout'] = popenArgs['stderr'] = PIPE
    +        popenArgs['stdin'] = stdin
    +        self.process = process = Popen(self.args, **popenArgs)
             self.signal_emit('before', process=process, loader=self)
             if self.input:
                 if py3:

**Comment by hut** [comment]
Done, thanks^^
