### ISSUE TITLE
Mime Type not working: "No action found."

### ISSUE THREAD

**Issue by BrunoVernay** [hut/ranger#354]
I had to edit `~/.config/ranger/rifle.conf` adding `ext cnf|java|sh|txt|py , label editor = $EDITOR -- "$@"`
to get the action.

I have `file-5.22` working and 
`ranger-stable 1.6.1
Python 2.7.10 (default, Jul  5 2015, 14:15:43) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
`

I tried to look at the source, but didn't find a way to kind of debug it.
Any hints ?

**Comment by hut** [comment]
So, what extension does the file have?

**Comment by BrunoVernay** [comment]
Sh or txt , I tested many. I saw that there are already rules for these,
but I guess that since mimetype is involved in the rule, it doesn't work.
That is why I had to add rules without mimetype.

**Comment by hut** [comment]
But mimetype is not involved. You just check for the extension. Something else must be wrong... Try to find out if the config file is being used at all.

**Comment by BrunoVernay** [comment]
That's the point: I had to add a rule without mimetype because the default
one, featuring mime doesn't work.

**Comment by hut** [comment]
Okay. What is the output of `file --mime-type -Lb <yourfile>`?

**Comment by BrunoVernay** [comment]
The issue is elsewhere: I removed my `~/.config/ranger/rifle.conf` and its working.

But doc says:
> ranger reads both the global config and the user's one (in that order). It allows the user to maintain only a small config which sets only the things not set in the default one. The best practice is to only add the options/keybindings you actually want to change

does it only apply to rc.conf and not riffle ?
(I also have a `~/.config/ranger/rc.conf` with a few changes, but it is working)

For now I copied the whole rifle.conf and added my change at the beginning.

**Comment by hut** [comment]
Yep, this only applies to some config files (rc.conf, commands.py) and not to others (scope.sh, rifle.conf). It's correct in the man page but incomplete in the wiki, I'm going to fix that. Thanks ^_^
