### ISSUE TITLE
Syntax Highlighting on Code Files?

### ISSUE THREAD

**Issue by x-ji** [hut/ranger#360]
Sorry if I've missed some instructions, but it seems that I've not been able to enable syntax highlighting for codes? In previews they're always displayed literally(plainly). However in the readme file there's "highlight for syntax highlighting of code", so I suppose there must be some way to achieve it. I tried to add in `scope.sh` code like

```
    md)
        try highlight --out-format=ansi "$path" && { dump | trim; exit 5; } || exit 2;;
```

but no luck.

**Comment by caipre** [comment]
`ranger` uses `highlight` to performan the syntax highlighting; do you have that program installed?

http://www.andre-simon.de/doku/highlight/en/highlight.php

**Comment by hut** [comment]
I'm closing this because it's an inactive support request. If this is still an issue, feel free to reopen it and continue the discussion.

**Comment by rosshadden** [comment]
I have `highlight` installed but `ranger` is not highlighting my code previews.  Is there configuration needed, or should it work out of the box if `highlight` is installed?

**Comment by hut** [comment]
You also need the scope.sh config file, copy it with `ranger --copy-config=scope`

**Comment by rosshadden** [comment]
That was it, thanks!
