### ISSUE TITLE
AttributeError: 'module' object has no attribute 'main' (Cygwin/Windows)

### ISSUE THREAD

**Issue by LoLei** [hut/ranger#362]
````
$ ./ranger.py
Traceback (most recent call last):
  File "./ranger.py", line 38, in <module>
    import ranger
  File "/cygdrive/c/ranger/ranger.py", line 39, in <module>
    sys.exit(ranger.main())
AttributeError: 'module' object has no attribute 'main'
````

OS: Windows 7 64bit Cygwin
Python: 2.7.10 (default, Jun  1 2015, 18:05:38)
Terminal emulator: ConEmu

After a fresh git clone I tried starting ranger.py, as the Readme.md suggests, and this error occured.

I did not find any related issues.

What is the recommended way of installing it on Cygwin?

**Comment by hut** [comment]
Try removing lines 33-35 (The part below `Don't import ./ranger ...`) from the file `ranger.py` and see if it helps

**Comment by hut** [comment]
Or just install it with `make install`, but I'm not 100% sure if this works on windows.

**Comment by LoLei** [comment]
Thank you, I will try these solutions tomorrow.

**Comment by LoLei** [comment]
After removing lines 33-35 in ranger.py the same error occurs:
````
$ ./ranger.py
Traceback (most recent call last):
  File "./ranger.py", line 38, in <module>
    import ranger
  File "/cygdrive/c/ranger/ranger.py", line 39, in <module>
    sys.exit(ranger.main())
AttributeError: 'module' object has no attribute 'main'
````

`make install` or `mingw32-make install` both did not work even yesterday, right now I can't try it because I somehow messed up my command line environment and it doesn't recognize commands such as `make` and `mingw32-make`, etc.

Nevermind though, I just realized I don't have "a pager" installed as your dependencies say, so it could be that.

**Comment by hut** [comment]
A missing pager would cause different errors. Also, you probably have the pager "less" installed.

Instead of `make install`, you can also write `python setup.py install --optimize=1`, that should work

**Comment by LoLei** [comment]
Seems to be almost the same error. 
````
$ python setup.py install --optimize=1
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import ranger
  File "/cygdrive/c/ranger/ranger.py", line 39, in <module>
    sys.exit(ranger.main())
AttributeError: 'module' object has no attribute 'main'
````

**Comment by hut** [comment]
What about this?

`PYTHONPATH=. python setup.py install --optimize=1`
