### ISSUE TITLE
Opening svg files?

### ISSUE THREAD

**Issue by ftzeng** [hut/ranger#363]
I have configured rifle for opening SVGs by adding the following line to top of my `~/.config/ranger/rifle.conf`:

    ext svg = feh --magick-timeout 1 -- "@"

The command works fine if executed manually with an SVG file.

However, if I highlight a file and hit "enter" in ranger to launch the file, I get the error "Failed to execute w3mimgdisplay". It seems somewhere `w3mimgdisplay` is being associated with SVGs, but I can't find where. Or is the issue something else?

I do have `set preview_images true` in my `rc.conf`, which works fine for other images.

**Comment by hut** [comment]
You're missing a `$` before the `@`, i.e. make it `ext svg = feh --magick-timeout 1 -- "$@"`

w3mimgdisplay is called when ranger attempts to preview the SVG file in the right column, so this error is unrelated to your problem.

**Comment by ftzeng** [comment]
Yep, that's all it was...thanks!
