### ISSUE TITLE
Should sorting respect LC_COLLATE?

### ISSUE THREAD

**Issue by caipre** [hut/ranger#365]
I prefer C style sorting of directory contents, but ranger doesn't seem to support this.

```bash
$ LC_COLLATE=C ls -aF --group-directories-first
.git/
FOO
Makefile
bar
zap
```

```bash
#
# ranger with sort=natural
#
.git
bar
FOO
Makefile
zap
```

**Comment by hut** [comment]
Check the option `sort_case_insensitive`

**Comment by caipre** [comment]
Ah, missed that one. Thanks, that suits perfectly.
