### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by arkhan** [hut/ranger#367]
Hello,

In the default configuration files(Vim-like) you can be launched with the keys 1l, which is equivalent to this in the alternate file(emacs-like).

Thanks

**Comment by hut** [comment]
I don't understand your intention

**Comment by arkhan** [comment]
When use default rc.conf(vim like), I can extract compressed files with 1+l, but on rc.conf (emacs like)  keys 1+l not work

**Comment by Vifon** [comment]
<kbd>M-1 C-f</kbd> seems to be working for me.

**Comment by hut** [comment]
fixed this in c5f96b080c8115201ce2b1ce055141c4e3e5039a, just fetch a new config from https://github.com/hut/ranger/blob/master/examples/rc_emacs.conf
