### ISSUE TITLE
how to compare/diff 2 directories before copying a lot of files?

### ISSUE THREAD

**Issue by collector1871** [hut/ranger#370]
hi
I have used midnight commander for years. Recently i changed it to ranger.

what is best way to:  
compare/diff 2 directories before copying a lot of files. Some of these files are the same (size), but they have different names.

is there any smart way to solve this problem by tmux? how to copy files from first tmux-ranger window to second?

**Comment by hut** [comment]
Ranger is not very good at diffing 2 directories and I recommend external tools like "meld".

But copying from one ranger instance to another is easy.

1. Select files to be copied in ranger instance 1 and type yy/dd
2. Run `:save_copy_buffer` in ranger instance 1
3. Run `:load_copy_buffer` in ranger instance 2

**Comment by collector1871** [comment]
Ok, your answer is excellent. I have also found nice free keys (unused) for mapping: 
http://ranger.nongnu.org/cheatsheet.png

`x`,`,`,`.`,`b`.

**Comment by hut** [comment]
@collector1871 You may be interested in `ranger --list-unused-keys`

**Comment by collector1871** [comment]
@hut 
yes. It is useful

**Comment by Bellavene** [comment]
Or chain it

```
map cc chain copy; save_copy_buffer
map vv chain load_copy_buffer; paste
```
