### ISSUE TITLE
counldnt' preview image without extension name

### ISSUE THREAD

**Issue by royaso** [hut/ranger#371]
ranger 1.6 
ubuntu package

if 'picture' is a image but without the '.jpg' extension name, preview dont work

**Comment by collector1871** [comment]
Try to look for a file called `scope.sh`. 
In my Debian it is located in:
`/etc/ranger/data/scope.sh` - this is symlink `/usr/share/pyshared/ranger/data/`.

**Comment by hut** [comment]
fixed in #372.

**Comment by royaso** [comment]
I used rxvt-unicode , w3mimgdisplay  to display images. It was fine , only problem is noe suffix name no image preview.

 After the fix , only img2txt no matter whether or not suffix name

**Comment by hut** [comment]
You need to update your ~/.config/ranger/scope.sh

**Comment by royaso** [comment]
@hut You are right! Thanks! IT works!!

**Comment by royaso** [comment]
@hut WHOA! I dont know why, but It gets better than I expected!!

I just try it in terminator which doesnt support images preview natively even though w3m-img is installed, But Now IT works with it too!! AMAZING!
