### ISSUE TITLE
how to change key ` to x ?

### ISSUE THREAD

**Issue by collector1871** [hut/ranger#374]
hi

How to change default bookmark-key to `x`?
This key is important in tmux (it is my prefix in tmux configuration).
I'd like to change 
`
to
x
in every behavior - how to do it?

edit: I've found this command: 
copymap ` x

it is working as i expect. But how to make it permanently in rc.conf?

**Comment by hut** [comment]
Just write that command into your `~/.config/ranger/rc.conf`, without the `:`.

**Comment by collector1871** [comment]
@hut 
Yes, you are right. I have tried
set copymap ` x
but it was wrong.
After that - this is my rc.conf:
```
copymap ` x
unmap `
```
and it is working. 

I've found similar, but ugly solution. From shell:
ranger --cmd="copymap \` x" --cmd="unset \`"
but it should be converted as bash alias... this solution is wrong.
