### ISSUE TITLE
Incredibly slow on sshfs or smbfs mounts when vcs-aware

### ISSUE THREAD

**Issue by sappel34** [hut/ranger#375]
ranger is a great a piece of software. But in my daily business it is unusable because of the poor performance when navigating network directories.
I have several sshfs mounts and smb mounts (mounted via autofs). Browsing this directories in shell or using midnight commander is very fast and responsive (less than 1 sec. for displaying a directory), browsing the same directories with ranger is a real pain (5 to 10+ seconds), sometimes ranger hangs completely.

The culprit seems to be vcs_awareness. As soon as it is disabled things work out fine.

**Comment by hut** [comment]
In the current version of the master branch, there was a big overhaul of the vcs integration with parallel loading.  Can you check if it is still slow?

**Comment by sappel34** [comment]
much better :) issue can be closed from my point of view.
