### ISSUE TITLE
image preview issue

### ISSUE THREAD

**Issue by IlikePepsi** [hut/ranger#376]
For some reason ranger cannot preview images on my arch linux machine. I doesn't work with w3m or iterm2. In debug mode I got this error when trying to preview an image.

    ranger version: 1.7.1, executed with python 3.4.3
    Locale: en_US.UTF-8
    Current file: /home/archuser/Pictures/3VJunqp.jpg
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
        fm.loop()
      File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 342, in loop
        ui.draw_images()
      File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 323, in draw_images
        self.browser.columns[-1].draw_image()
      File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/pager.py", line 97, in draw_image
        self.fm.notify(e, bad=True)
      File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/pager.py", line 93, in draw_image
        self.wid, self.hei)
      File "/usr/lib/python3.4/site-packages/ranger/ext/img_display.py", line 143, in draw
        sys.stdout.write(curses.tparm(curses.tigetstr("cup"), start_y, start_x))
    TypeError: must be str, not bytes

**Comment by thisch** [comment]
Try to replace ``curses.tigetstr("cup"), start_y, start_x)``  by ``curses.tigetstr("cup"), start_y, start_x).decode('utf-8')`` in  ``/usr/lib/python3.4/site-packages/ranger/ext/img_display.py`` and check if this works.

**Comment by IlikePepsi** [comment]
No it doesn't work. Seems like the picture is getting decoded to characters.

![ranger_image_preview](https://cloud.githubusercontent.com/assets/9033437/10071672/df0019a2-62bb-11e5-9b3a-3bcabaec373b.png)

**Comment by IlikePepsi** [comment]
When using w3m as previewing method I get the following error:

    ranger version: 1.7.1, executed with python 3.4.3
    Locale: en_US.UTF-8
    Current file: /home/archuser/Pictures/3VJunqp.jpg
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
        fm.loop()
      File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 342, in loop
        ui.draw_images()
      File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 323, in draw_images
        self.browser.columns[-1].draw_image()
      File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/pager.py", line 97, in draw_image
        self.fm.notify(e, bad=True)
      File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/pager.py", line 93, in draw_image
        self.wid, self.hei)
      File "/usr/lib/python3.4/site-packages/ranger/ext/img_display.py", line 67, in draw
        start_y, width, height))
      File "/usr/lib/python3.4/site-packages/ranger/ext/img_display.py", line 108, in     _generate_w3m_input
        raise Exception('Failed to execute w3mimgdisplay', output)
    Exception: ('Failed to execute w3mimgdisplay', [])

I checked the `W3MIMGDISPLAY_PATH` variable in img_display.py and it points to `/usr/lib/w3m/w3mimgdisplay ` which is the right path. So could this be some kind of permission error?

**Comment by hut** [comment]
First of all, try updating your scope.sh if you run the git version of ranger

**Comment by IlikePepsi** [comment]
Ok, so I was using the version distributed by Arch Linux. The PKGBUILD uses the tar.gz-archive from http://ranger.nongnu.org/ranger-1.7.1.tar.gz. Perhaps this should be changed to the ranger-stable.tar.gz file. Eventually I'll file a bug.

I switched to use the ranger-git package from the AUR (Arch User Repositiry) and now I get some output but it's allways ascii-art. I thought w3m would render the pictures in full color and pixels. I mostly use terminator as console emulator but even with xterm and the gnome-terminal it's always ascii.

**Comment by oliverpool** [comment]
> now I get some output but it's allways ascii-art

You changed the [rc.conf](https://github.com/hut/ranger/wiki/Image-Previews), right?

(I'm using the arch distributed ranger, and everything worked fine)

**Comment by hut** [comment]
If this is still an issue, please join the IRC channel (#ranger on freenode) for a quicker discussion.

**Comment by IlikePepsi** [comment]
Hi again,

I checked again if I made any mistakes with the configuration, please verify.

Here are the required packages installed on my machine..
![pacman_packages](https://cloud.githubusercontent.com/assets/9033437/10631454/6fa00b8e-77de-11e5-851d-2852b4b241d9.png)

Here is a snippet from my rc.conf file..
![rc conf_snippet](https://cloud.githubusercontent.com/assets/9033437/10631474/9d39751c-77de-11e5-9030-76f09778b5de.png)

And last but not least, the image preview I get within ranger..
![ranger_image_preview](https://cloud.githubusercontent.com/assets/9033437/10631494/b216fa68-77de-11e5-85e2-57b25a3e21f5.png)

Are there any other places where some rogue configuration could cause this behavior? If not, I'll join your IRC. Thx in advance.

**Comment by tex** [comment]
I have the same problem. It used to work ok, but after some update all I get is text based image preview.

**Comment by eyolf** [comment]
Same problem here. I'm also running the git version from AUR
I believe the problem started with this update:
[2015-10-10 04:39] [ALPM] upgraded ranger-git (1.7.1.63.g946ff7e-1 -> 1.7.2.42.g91d784a-1)

**Comment by Vifon** [comment]
Is your `scope.sh` up to date?

**Comment by eyolf** [comment]
It is now, and it's working again. What a coincidence! :)
Thx

**Comment by tex** [comment]
Oh, it fixed it for me too. :-)

Thanks

**Comment by IlikePepsi** [comment]
Deleted all files in `~/.config/ranger/`, reinstalled ranger-git package from AUR, executed `ranger --copy-config=all` to get fresh config files, set `preview_images` to `true`, still get only ascii-pictures.

**Comment by astrohckr** [comment]
@IlikePepsi 

I was experiencing a similar issue. I worked around it by modifying `scope.sh`; you can see my changes at this [gist](https://gist.github.com/astrohckr/4c6293203af01b30fd8f).

When running `ranger` and then trying to preview an image, it would default to the `img2txt` because `preview_images` is not being set or read as a value by `scope.sh`.

**Comment by IlikePepsi** [comment]
I upgraded to the latest git-version today (from AUR) and used the same procedure as in my last post and the issue is gone. Pictures are rendered correctly. Thanks for all your time and help.
