### ISSUE TITLE
top bar shows a python FutureWarning 

### ISSUE THREAD

**Issue by ngoonee** [hut/ranger#381]
Copied from Arch bug-report (by me) - link https://bugs.archlinux.org/task/46469

Description:
On starting up ranger, it shows on the top bar the following:-

loading.../usr/lib/python3.5/site-packages/ranger/container/fsobject.py:152: FutureWarning: split() requires a non-empty patter match.

Resizing the terminal fixes it.

This is with ranger from [testing] (rebuilt for python 3.5)

Additional info:
* package version(s)
ranger-1.7.1-2

Steps to reproduce:
Just run ranger

**Comment by Enzime** [comment]
From testing, it is a result of the `_extract_number_re = re.compile(r'([^0-9]?)(\d*)')` regex on line 33 of `ranger/container/fsobject.py` and only occurs in certain directories. As far as I know, all that resizing the terminal does is redraw the screen which results in the error not being displayed anymore (error also disappears when running `:redraw_window`).

The error only occurs in some folders from what I've seen

**Comment by motdef** [comment]
I have the same issue on Arch and it seems to occur in any folder

**Comment by nr1q** [comment]
For me it shows any folder where I run ranger; after a clean it shows again but in some folders.

**Comment by AnderRasoVazquez** [comment]
I have the same problem.

**Comment by sim590** [comment]
I'm expreriencing this too. It seems to happen after updates of some python packages. Since it's written `FutureWarning`, I guess it may be related to the python3.4 -> python3.5 update. I'm just throwing this here. I don't have any further information.
