### ISSUE TITLE
startup warning : _extract_number_re.split

### ISSUE THREAD

**Issue by aureooms** [hut/ranger#386]
Starting ranger now shows the following warning message
![2015-10-03-133334_1251x41](https://cloud.githubusercontent.com/assets/5165674/10262702/8fc12f2e-69d3-11e5-843b-6408b73241c4.png)

Seems related to http://stackoverflow.com/questions/29988595/python-regex-splitting-on-pattern-match-that-is-an-empty-string.

**Comment by shaggytwodope** [comment]
duplicate of #381

**Comment by hut** [comment]
Fixed in #385
