### ISSUE TITLE
1.7.2 image previews not working any more

### ISSUE THREAD

**Issue by sappel34** [hut/ranger#392]
After updating from 1.7.1. to 1.7.2 the image preview doesn't work anymore. 
Starting ranger with -d option to see possible crash did'nt reveal anything. Starting ranger with -c option to exclude config problem didn't help. Any idea how I can diagnose the problem?
w3mimagedisplay is installed and path in img_display.py is correct.

**Comment by Ambrevar** [comment]
Image preview works fine by me on 1.7.2.
After running `ranger -c`, did you run `set preview_images True`?

**Comment by hut** [comment]
You probably use ranger-git, right?
Update your scope.sh as described in https://lists.nongnu.org/archive/html/ranger-users/2015-09/msg00000.html

**Comment by sappel34** [comment]
Updating scope.sh solved the issue! Thanks for the great support and the great tool !

**Comment by adam8157** [comment]
How about making the scope.sh update smoothly/automatically? I won't know that trick unless subscribed maillist or github activity. Thanks.

**Comment by Vifon** [comment]
User could have customized his scope.sh. Overwriting it would be bad.

**Comment by hut** [comment]
scope.sh is pretty much like a black box that ranger uses to generate previews. The only way to add a compatibility layer is to use dirty heuristics, e.g. to use different ranger<->scope.sh interfaces depending on whether certain strings occur in scope.sh, which are unique to the old and the new scope.sh respectively. It's a mess either way. Any ideas on how to solve this?

Automatically overwriting scope.sh is no option for the reason vifon gave.

**Comment by Vifon** [comment]
In the future adding a version string to scope.sh should ease the migration. It could be possible to check how old is the copied file and inform the user if it is no longer compatible.

**Comment by Ambrevar** [comment]
+1
