### ISSUE TITLE
list of keybindings, commands and settings do not appear

### ISSUE THREAD

**Issue by citrusLover** [hut/ranger#413]
I installed this version of ranger on my Xubuntu machine
```
ranger-stable 1.6.0

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
```

When I type `1?`, `2?` or  `3?` nothing happens, the keybindings, commands and settingslist is do not appear. If I type `?` the man page does appear.
When I close ranger the following message is shown for each try (so if I tried 4 times to type `1?` this messages is displayed four times):
```
Failed to run: ['sensible-paper', '/tmp/tmptOGjWY']
[Errno 2] No such file or directory
```

**Comment by Vifon** [comment]
It seems you don't have the `sensible-pager` program installed. AFAIK the Debian ranger package contains the patch that enables the usage of the `sensible-pager`. I've just installed a fresh Xubuntu and it contains `sensible-pager` out of the box. You must have removed it one way or another.

**Comment by boutkan** [comment]
sensible pager is installed on my system.
```
$ which sensible-pager 
/usr/bin/sensible-pager
```
When I execute `sensible-pager someDocument` I can see the document in less.
It seems to me that the pager is working but the files (with the keybindings, etc) are gone.

**Comment by Vifon** [comment]
I've just saw it... The error message has `sensible-paper`. Paper, not pager. I'll check the 1.6.0 package for (X)ubuntu in a minute. Which Xubuntu version are you running?

**Comment by citrusLover** [comment]
I am running `14.04.3 LTS`.

I checked and `sensible-paper` is not installed on my system. A quick sudo apt-get install sensible-paper didn't work (unable to locate package), so I am trying to find the package and install it.

**Comment by citrusLover** [comment]
Ah, now I understand your message.
I found the following bug report: https://bugs.launchpad.net/ubuntu/+source/ranger/+bug/1331444
Seems to be the same problem.

**Comment by citrusLover** [comment]
I've just built the program manually (sudo make install) and then it works just fine so the error seems to be in the package.

**Comment by Vifon** [comment]
That's what I've concluded too but for some reason the comment was not sent.
Yeah, the error is in one of the vendor patches supplied with the Ubuntu package, not in ranger itself.

For the record, my original comment:

> Yeah, it's a bug in the 1.6.0 package. The 1.6.1 package has it already fixed. It's not the upstream bug. Is upgrading to 1.6.1+ an option for you?

**Comment by ZirconCode** [comment]
Thanks! Problem solved. Just in case anyone is searching, this is how the error looks in fish:

    ??man: command exited with status 255: (cd /home/username && LESS=-ix8RmPm Manual page ranger(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page ranger(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=ranger(1) sensible-paper)
