### ISSUE TITLE
Macro with :rename

### ISSUE THREAD

**Issue by kurkale6ka** [hut/ranger#417]
Hello,

I have these two files: `A.avi` and `foo`. I want to rename `foo` to `A.srt` (`foo -> A.srt`).
So I selected `A.avi` with space and highlighted `foo`, and tried `:rename %s.srt`.
Result: I got a file called `%s.srt` instead of the expected `A.srt`.
I managed with `:shell mv %f %s.srt` but that's much more work.

What I tried should be possible, right? This is what the man page read:

`Macros can be used in commands to abbreviate things`

Cheers

**Comment by dquinton** [comment]
Don't understand why you selected "A.avi" it you don't want to rename it.

":rename" is exactly that, like bash `rename file newname`

so in your case, its like `rename foo %s.srt` as ":rename" acts on only 1 file, the highlighted

what you should do: highlight file `foo` (no need to select it) and type `cw`, enter new name, Enter

It you want to rename a file with same name as another file, highlight the file with name you want to copy, `yn` then go to file to rename and `cw` - then you need to paste from clipboard into the console - which I'm not sure ranger supports?

I have a keybind on my system to allow pasting from clipboard into a terminal or ranger console, like this
`sh -c 'xsel -b | xvkbd -delay 4 -xsendevent -file -'`

**Comment by kurkale6ka** [comment]
Hmm, I was wrong, in fact `:rename %s.srt` would rename `foo` to `A.avi.srt`.
I guess should stick to using `:shell mv %f %s.srt` or `yn`, `cw`,... but the help should definitely be amended

**Comment by dquinton** [comment]
ah, now I see your principle, but yeah, %s includes the ext, so it can't really work as you tried

**Comment by hut** [comment]
How should the manual be fixed?

Also, I recommend the magic keys I and A for "insert before the filename" and "append after the filename".

**Comment by kurkale6ka** [comment]
Well, the manual reads `Macros can be used in commands to abbreviate things` but clearly `%s` can't be used with `:rename`

**Comment by dquinton** [comment]
+1 for A and I, very useful keys

kurkale, the manual is correct then, isn't it? `%s` inserts the selected filename, including its extension... if there was a macro for filename without extension... but not that I know of..

how about with a bash script...
`mv $1 "${2%.*}.${1##*.}"`

ranger: `rename-with-selected %f %s`

I tested it and it works - Select file you want to use its name, Highlight file you want to change name - %f is passed to bash $1 and %s will be $2

I think I'll add this to my mapping :)

**Comment by Vifon** [comment]
I might add that 'a' is a great key too: It places the cursor just before the file extension. A few presses of <kbd>ctrl+w</kbd> should do the job.

**Comment by kurkale6ka** [comment]
@dquinton I am not sure you read my posts. I said expecting `A.srt` instead of `A.avi.srt` was wrong but neither works. `%s` isn't supported and this is my whole point.
Why would I want your overly complex and long solution if I stated in my very first comment that `:shell mv %f %s.srt` works?

**Comment by dquinton** [comment]
because `mv %f %s.srt` makes a file with extension of %s inside its name

**Comment by kurkale6ka** [comment]
yes, apologies, I got carried away and thanks for your suggestion but I don't want a bash solution if I am within ranger. I will use for now your `yn`, `cw` suggestion

**Comment by dquinton** [comment]
man, I forgot about simple `a` , v useful

**Comment by dquinton** [comment]
that's alright, and yeah, it's nice to stay in ranger - and usually bash can run straight in the console, but sometimes it doesn't because ranger confuses macros and the like - like it wouldn't recognise the `%.*` just now so I had to make a script.

**Comment by kurkale6ka** [comment]
Maybe something like Vim's `:r` (`:h::` within Vim) could be added @hut?
Although I would call it `:n` for name
Then we could type stuff like: `:rename %s:n.srt`

**Comment by hut** [comment]
macros were explicitly disabled for `:rename` in dfc0c61ad371d73a7fce842f8196fb2cef081f1d.

I'm not sure anymore why, but I think it was so you can use the `A` key on files with a `%s` in the name without things breaking. I'm going to revert the patch and write a better workaround.
