### ISSUE TITLE
Image previews on x86_64 linux

### ISSUE THREAD

**Issue by kinclma1** [hut/ranger#418]
Hello, the path to `w3mimgdisplay` seems to be hardcoded in `img_display.py` as `/usr/lib/w3m/w3mimgdisplay`.

On my 64bit system, however, it is in `/usr/lib64`.

Is it possible to make it look up the file in the `lib64` directory if it's not found in `lib`?

**Comment by shaggytwodope** [comment]
Curious what distro this occur on?

**Comment by hut** [comment]
Change the `W3MIMGDISPLAY_PATH` environment variable, see man page

**Comment by kinclma1** [comment]
@shaggytwodope it's openSUSE

@hut Sorry, I should have read the manual till the end. I just thought it would be nice if it worked out of the box.

**Comment by hut** [comment]
It works out of the box now, FYI.
