### ISSUE TITLE
osx can't use alt-<n> to switch tab

### ISSUE THREAD

**Issue by mushanshitiancai** [hut/ranger#420]
my environment：
- OSX EL Capitan 10.11.1
- iterm 2.1.4

I install ranger through brew. I can't use alt-<n> to switch tab,why?

**Comment by hut** [comment]
I'm not familiar with iterm but on xterm there's the same issue and it can be fixed by setting `xterm_alt_key` to true, e.g. by adding this line at the end of `~/.config/ranger/rc.conf`:

`set xterm_alt_key true`

Try it out and see if it works for you.

**Comment by mushanshitiancai** [comment]
@hut thank you,but `set xterm_alt_key true` doesn't work to iterm2.

in iterm2,the solution is:

![qq20151214-0](https://cloud.githubusercontent.com/assets/4251771/11771829/91f02286-a250-11e5-91e3-ada94d2fba84.png)
