### ISSUE TITLE
Deploy script to /etc/profile.d so ranger can change pwd

### ISSUE THREAD

**Issue by blaskovic** [hut/ranger#425]
Hi,

do you considered the option of deploying script to /etc/profile.d which would ranger allow to change current working directory? As midnight commander does.

**Comment by hut** [comment]
If you use bash, you can use this script by sourcing the ranger executable like `. ranger`.  This will not work if your package manager installs a different executable file.

Then, there is `/usr/share/doc/ranger/examples/bash_automatic_cd.sh`.

**Comment by blaskovic** [comment]
Ah thank you, so we have this script it is just not deployed automatically.
Why you do not install this by default?

**Comment by hut** [comment]
I wasn't aware of `/etc/profile.d`. Good idea, actually. Does anybody see a problem with this?

**Comment by blaskovic** [comment]
The only issue I can see is with ctrl+o binding. I am not sure if it is common that installed application is changing my key bindings.

**Comment by Vifon** [comment]
Disclaimer: I'm not an expert in that matter. This is just my reasoning.

First of all `/etc` is placed outside of the installation prefix. It might be tricky to properly handle it in various scenarios (for example when running without the root privileges). One way would be to use `$PREFIX/etc` (which I don't think is a standard directory) and let the user to copy the scripts but it wouldn't change much considering the scripts are already in `$PREFIX/share/doc/ranger/examples` and can be copied from there as well.

Secondly, `/etc` is highly dependent on a specific distribution and vice versa. I believe it would be more appropriate to contact the ranger maintainer for a given distribution. And even then I think it's the administrator's job to enable such scripts globally.

**Comment by hut** [comment]
I'm closing this, because it doesn't seem like a good idea to automatize it.
