### ISSUE TITLE
moving up/down by parent

### ISSUE THREAD

**Issue by dquinton** [hut/ranger#426]
Hi, firstly, ranger is an awesome work!

The move by parent action is something I find very useful, and I've been trying to make new keys to move up/down the parent level by 5 dir (I map { and } ) and by 20 dir (I map F9 and F10 -so yes I scrub the MC mapping).  I guess move by parent to top and end would be good too.

The best I can do is this - and it works OK, but it's messy and it makes the directory history useless because it is basically multiple "move parent"...

`map {	 chain move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1`
`map }	 chain move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1`
`map <F9>     chain move_parent 1; move_parent 1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1; move_parent -1`
`map <F10>    chain move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1; move_parent 1`

So is there a better way?  Or could `move_parent` be improved to accept the following...

`move_parent down=5`
`move_parent up=5`
`move_parent down=0.5  pages=True`
`move_parent up=0.5  pages=True`
`move_parent to=-1`
`move_parent to=0`

cheers

**Comment by hut** [comment]
5[ moves up 5 steps. you can bind this to a key with the "n" keyword:

`map { move_parent n=-5`

**Comment by dquinton** [comment]
that's cool, I had missed that, n[ , thanks
