### ISSUE TITLE
Bulkrename doesn’t work with atom-editor

### ISSUE THREAD

**Issue by andya9** [hut/ranger#432]
I’m on archlinux; ranger from git.
If I change this string in commands.py:
> self.fm.execute_file([File(listpath)], app='vim')

to:
> self.fm.execute_file([File(listpath)], app='geany') # or atom-editor

when I call bulkrename it exits with errors: Geany complains about not finding the tempfile on disk, then when I close it nothing happens. With Atom ranger gives No renaming to be done, then Atom opens an empty buffer.
Is it because they are gui applications?

**Comment by hut** [comment]
geany works for me.

Your behavior would occur if the editor forks to background as soon as its started, so ranger thinks you're done editing and deletes the tempfile, before the editor has time to accesss it.

For me, geany blocks the terminal until I close it, but maybe for you it doesn't? That would explain it.

Either way, I can't think of a good solution to fix this.

**Comment by andya9** [comment]
I got the problem with geany: I was trying the command after setting geany instead of vim *without* closing geany first.. it just needed to be restarted! 
Now I try atom

**Comment by hut** [comment]
Maybe atom has one single global instance, and when you open the file created by `:bulkrename` in atom, it only tells the main atom process to open it, rather than creating a new atom process.

`:bulkrename` needs the editor to block until editing is finished.

**Comment by andya9** [comment]
@hut 
Atom has a "wait" flag for this. I tried to pass it, but the editor will open a new blank file. What’s good: now it simply opens, whereas without the flag it will open a blank file with a strange temporary name (e.g. /tmp/tmp2joerztx), and before that ranger will say "No renaming to be done!".

**Comment by hut** [comment]
Any success yet?

**Comment by andya9** [comment]
Nothing. But I think the bug is in atom, not ranger: there’s [this](https://github.com/atom/atom/issues/3074) issue that could be responsible (i.e., the --wait flag doesn’t actually wait).

**Comment by hut** [comment]
Yep, thanks for your research!
