### ISSUE TITLE
Qs: how to address selected files from different directories

### ISSUE THREAD

**Issue by amerlyq** [hut/ranger#434]
I know, I can select by ```<Space>``` list of files in current dir and then apply to them something like ```:shell -w echo %s```. I hoped, that by using tag marker on ```t``` I will not be bounded to current directory, but it's not the case. Command ```:shell -w echo %t``` shows only tags in current directory.
How could I mark files in several different directories and apply command to them (for example -- to use grep/vim/sed).

**Comment by hut** [comment]
Selections are local, whereas copied files are global. So you can just copy files in dir A with `yy`, go to dir B and adress the copied files with `:shell -w echo %c`. You can even add further files from dir B to the copy buffer with `ya`.

**Comment by amerlyq** [comment]
Thanks for fast reply. 
It's somehow unintuitive to use copy list for such tasks, but to be able to do whatever relative is nice anyway. 
I think in the end I have misunderstood using tags at all. Their purpose at least.
Could you then point me out to some useful usage examples -- yours/community -- anything related?
Because there are not much info inside man, and barely nothing on web. Seems like no-one use it?

**Comment by hut** [comment]
Sure. I view the difference of two files by doing a `yy` on file 1, then move to file 2 and call this key binding:
`map diff shell diff -r %c %f | less`

**Comment by amerlyq** [comment]
I do same by supplying ```%s``` or ```%f %F```, but yours not bad either.
Hm, and what about using tags ```%t```?

**Comment by hut** [comment]
oh, `%f %F` is a good alternative :)!

tags are not meant for this. they are useful in combination with `:setintag` or for visual hints, e.g. you could tag all the videos of a series that you have already watched.

**Comment by amerlyq** [comment]
Alright, now I somehow understand tags purpose. 
It's some kind of attribute markers and not selection.
What left is to think of how to use it and what in workflow can be optimized with them.
