### ISSUE TITLE
Navigation mode

### ISSUE THREAD

**Issue by mightyCelu** [hut/ranger#436]
I find myself navigating to locations I visit often by repeatedly entering search mode plus a prefix of the location I want to visit.
Would it be possible to add a navigation mode that works similar to the search mode, but:
-  persists until it is disabled
- resets the prefix after every vertical navigation opertaion
- visually highlights the possible valid entries (or displays the non-matching entries in a less prominent font)
- allows to navigate using the normal navigation keys in the list of valid entries

At least for me this would greatly increase the usability.

**Comment by hut** [comment]
Check out `:travel` and `:scout`. `:travel` is just `:scout` with the options `-aefiklst` but you can customize it to your need.

**Comment by mightyCelu** [comment]
Thanks for pointing that out, travel seems to work as I want it to. Next time I should read the documentation more properly....
