### ISSUE TITLE
w3m image instantly disappears on any input event

### ISSUE THREAD

**Issue by amerlyq** [hut/ranger#440]
After image is shown, any keyboard or mouse event clears w3m preview image from viewport.
Moreover, using `sleep 5 && scrot ...` from another teminal window also clears preview.
It's weird. Is it fixable? Or there is some insurmountable problems?

**Comment by hut** [comment]
The way w3m implements previews is a huge mess anyway. Not much we can do about it. But usually it helps to try out different terminals, urxvt works particularily well for me.
