### ISSUE TITLE
setlocal (path) sort mtime is recursive. Is there a way to make it only work on specific directories?

### ISSUE THREAD

**Issue by krompus** [hut/ranger#443]
In rc.conf, I have

    setlocal path=~/downloads sort mtime
    setlocal path=/mnt/blue/downloads/torrents sort mtime

...which is super handy, and organises my downloads by the time I acquired them, most recent at the top. Unfortunately, it also applies to subfolders, like [this (top right, magenta)](https://i.imgur.com/umhevg3.png).

Is there way to specify this sort option to apply only to specific directories, non-recursive?

EDIT: I just thought of something. Perhaps another rule like

    setlocal path=/mnt/blue/downloads/torrents/* sort natural

...that would specify that all folders inside this directory are to be sorted another way? I tried the line above, but it didn't work.

Also, it seems that the rules I've listed above override manual sorting. IE, I can't use `o` sort commands inside `/mnt/blue/downloads/torrents` or any of its child directories.

Perhaps I've found a bug?

**Comment by hut** [comment]
The path is a regular expression. I'm surprised it's not documented anywhere, I'm gonna fix that.

If you don't know regular expressions, just try to use something like `path=~/downloads$`.

**Comment by krompus** [comment]
wow
         very fix                              much program

                                     so help

**Comment by krompus** [comment]
:P

Thank you!

**Comment by hut** [comment]
You too, fellow jellyfish

**Comment by krompus** [comment]
*bloop bloop*

:(){ :|:& };:

**Comment by manujchandra** [comment]
I have spaces in my path:

`setlocal path='/home/manuj/Productivity_System/04 BIN/04 RA RP SP/002 RELIEVING'$ sort mtime`
`setlocal path='/home/manuj/Productivity_System/04 BIN/04 RA RP SP/002 RELIEVING'$ sort_reverse true`

This is fixing the parent part. That is the folders above 002 RELIEVING can be sorted individually. But the subfolders of 002 RELIEVING are still getting sorted as per parent.

I tried moving $ within quotes but that did not work. Tried with ~ and " also did not work.
