### ISSUE TITLE
Bookmarks aren't updated on renaming

### ISSUE THREAD

**Issue by evgorchakov** [hut/ranger#447]
It appears that if a directory is bookmarked and then renamed (via `:rename` or `:rename_append`), the bookmarks file isn't updated, which leads to that particular bookmark becoming inaccessible since that particular directory ceases to exist. Is this by design? If not, could there be an option to update the bookmarks file on renaming? I'm willing to work on it if necessary.

**Comment by charignon** [comment]
I sent #469

**Comment by hut** [comment]
Fixed in #469, thanks @charignon

**Comment by hut** [comment]
Though it doesn't work yet if you rename the parent directory...

**Comment by charignon** [comment]
That's right, I was planning to send another patch for that.
