### ISSUE TITLE
`Invalid value `draw_borders' for option `true '!` error OSX

### ISSUE THREAD

**Issue by srustamo** [hut/ranger#450]
Changing `set draw_borders true` from `set draw_borders false` in rc.conf (after `ranger --copy-config=all`) shows `Invalid value 'draw_borders' for option 'true '!` error after quitting.

Changing some other options work, e.g. `set column_ratios 1,1,4`. 

OSX

**Comment by hut** [comment]
maybe you have a trailing whitespace after the "true"?

**Comment by srustamo** [comment]
Indeed.
