### ISSUE TITLE
Adding Ctrl-LeftArrow/RightArrow functionality to jump words

### ISSUE THREAD

**Issue by Risto-Stevcev** [hut/ranger#473]
It would really cool if ranger could jump words using Ctrl-LeftArrow/Ctrl-RightArrow during something like `:rename`, like you can with vim `:rename` (and GUI-based managers), so that you could quickly get to end of a specific word and save a bunch of time rather than holding down RightArrow until you reach it.

**Comment by larghetto** [comment]
+1.

**Comment by hut** [comment]
Just added it. Couldn't bind it to ctrl+left/right, so I bound them to alt+left/right instead. https://github.com/hut/ranger/commit/33abb9feca7ff5fde9afebba744a575436d71656
