### ISSUE TITLE
editor invocation fails: `dyld: Library not loaded: /usr/local/lib/libruby.2.2.0.dylib` OSX

### ISSUE THREAD

**Issue by srustamo** [hut/ranger#475]
After upgrading ruby to 2.3.0 on OXS with `brew upgrade ruby` $EDITOR invocation fails:

    dyld: Library not loaded: /usr/local/lib/libruby.2.2.0.dylib
    Referenced from: /usr/local/bin/vim
    Reason: image not found
    /bin/sh: line 1: 30149 Trace/BPT trap: 5       $EDITOR -- "$@"

**Comment by srustamo** [comment]
This seems like a Vim problem on my system.

**Comment by sloansparger** [comment]
I'm having this same issue. Were you able to figure out what it was?

**Comment by srustamo** [comment]
I either tweaked ruby paths (vaguely remember doing something with *rbenv*), or reinstalled *vim* from *homebrew*. Sorry, can't be more specific.
