### ISSUE TITLE
SFTP?

### ISSUE THREAD

**Issue by krompus** [hut/ranger#476]
I have a friend who might be interested in switching from Midnight Commander to ranger, if there's a way to use SFTP.

Is there any way you know of?

**Comment by RShadowhand** [comment]
I'd like to know too, please. MC is too slow for my tastes, and I actually enjoyed Ranger.

**Comment by lamarpavel** [comment]
If you can use SSH instead of SFTP, then you can use ranger in combination with SSHFS. Other than that, I haven't heard of any explicit networking integration with ranger.

**Comment by RShadowhand** [comment]
Well, SFTP uses SSH port. I'd rather not use SSHFS. A lot of things can go wrong with that.

**Comment by lamarpavel** [comment]
Yeah, it's not really a viable alternative. I would like to see some native integration as well, but @hut has very little time currently. If I had the time to delve into it and get sufficient enough in Python I'd probably look at it, but for now I'm stuck with manual SSH as well.
For local networks NFS + ranger works pretty well though.

**Comment by hut** [comment]
Closing because it's duplicating #83.
