### ISSUE TITLE
Filter - Semi-persistent mode

### ISSUE THREAD

**Issue by vitalybe** [hut/ranger#479]
Currently scout allows 2 filters modes: 

- Persistent - Allows to filter and then easily work with the results, choosing the right file, etc. However, the filter remains also when changing directories. This can lead to confusion as it isn't immediately obvious that the folder you're looking at is filtered, especially if you've set the filter a while ago.
- Not-persistent - The filter is shown only until you press Enter, which means you can't navigate filtered the results.

 Is there a way to create a filter but clear it as soon as the folder changes? If not, I think it would make a nice enhancement.

**Comment by hut** [comment]
Thanks :D

**Comment by hut** [comment]
Merged, thanks. Pro-tip: if you put "fixes #479" somewhere in the commit message, it automatically closes the issue report.

**Comment by vitalybe** [comment]
Noted :) Thank you

**Comment by vitalybe** [comment]
Closed by #486
