### ISSUE TITLE
No preview when copying scope file

### ISSUE THREAD

**Issue by OskarPersson** [hut/ranger#482]
When I run `ranger --copy-config=scope` (for enabling image previews) no previews work at all. If I remove the config files from `~/.config/ranger` they work again (though not images).

**Comment by hut** [comment]
Have you been following the guides on the github wiki?

**Comment by OskarPersson** [comment]
Yes I followed what is written here

**Comment by hut** [comment]
Could be anything. If you're still interested in solving this, log on IRC (#ranger on freenode) and we can debug this together.
