### ISSUE TITLE
copy mode = remove <yr> isn't working after file has been pasted

### ISSUE THREAD

**Issue by jarhat** [hut/ranger#483]
When a currently selected file is yanked with yy, the copy mode can be removed again with yr, that's alright..
But after having it pasted with pp, the copy mode cannot be removed with for some reason.
The file stays grey (in default colorscheme) and can still be pasted. To sort of clear the 'yank buffer', I could only yank another file and remove the copy mode here.

I'm having this with ranger 1.7.2.

**Comment by hut** [comment]
Fixed by #526
