### ISSUE TITLE
Show quick shell (s) output and exit status somewhere

### ISSUE THREAD

**Issue by cirosantilli** [hut/ranger#485]
When I hit `s`, I can enter a single command really fast.

But that is hard to use since I don't see the output and exit status.

Please give us some way to see it. E.g.:

- vim style: click enter to dismiss if longer than one line / show on status otherwise
- show on the preview pane until any new key is pressed

Tested on 1.6.1.

**Comment by hut** [comment]
You can use `:shell -w ls` to view the output of ls until you press enter. See man page, section `FLAGS`,

**Comment by nobk** [comment]
Can you give a keybinding switch cmd output screen back and forth? mc can using Ctrl+o to do this.

**Comment by Artalus** [comment]
@hut from the likes given to nobk it seems that it'd be a useful feature. It is pointless to rebind `s` to always use `:shell -w ` instead of `:shell `, yet it is a very frequent task to check the output of the last executed command.

**Comment by toonn** [comment]
Why toggle the behavior of `s`? You can just come up with another keybinding, for example you could rebind `!` since it's redundant with `s` anyway: `map ! console shell -w%space`.
Another alternative is just to use `S` when you want to see the output of commands you executed with `s`, it's why I never use `:shell -w`.

For those who really want the toggling behavior, write a custom command, or come to the irc and nag about it until one of us does ; )

**Comment by Artalus** [comment]
My point was that sometimes you need to see output of shell that was started without `-w`. But `S` is a nice workaround indeed, I've never noticed that it actually preserves the command outputs, not only history of what happened in a previous session.

**Comment by toonn** [comment]
That's how it's always worked for me. Being able to view the output of the last command would require buffering that output. I think currently `-w` just appends `| $PAGER`.

**Comment by nadapez** [comment]
To see the (internal) console output press `W`

To see the **shell** output  press S which execute the default shell ($SHELL). Then get back pressind <c-d> or type exit.

Alternatively you can map a key to the command `shell -w :` ; that executes a dummy `:` in shell and wait for user to press enter.
for example:
```
map <c-o> shell -w :
```
