### ISSUE TITLE
Ranger cause Joe to go into Startup Log

### ISSUE THREAD

**Issue by peterjschroeder** [hut/ranger#493]
Distribution: Debian Sid
Ranger: 1.7.1
Joe: 4.1

Recent upgrade of Ranger and/or Joe caused Ranger to cause Joe to go into Startup Log. Ranger passes -- to Joe which was probably ignored before. Recent Joe has a Startup Log that catches issues. It shows -- as an issue every time I edit a file or call batchrename. Removing -- from rifle.conf in the edit sections solves this issue.

**Comment by hut** [comment]
I consider this a failure of joe. Most editors support `--` and it actually helps preventing security issues, so I won't remove it from the defaults, sorry.
