### ISSUE TITLE
how do I escape newlines in rifle.conf?

### ISSUE THREAD

**Issue by sharethewisdom** [hut/ranger#494]
Hi,
this may be a redundant question. I have some long lines in `rifle.conf`. Is there a way to split the list of conditions or the part after `=`?
maybe something like:

```sh
<condition1> , <condition2> , ... = command --option 'first' \
                                 += --other 'stuff'| \
                                 += xargs blahblah
```

**Comment by hut** [comment]
not possible atm ;(
