### ISSUE TITLE
New screenshot for the website

### ISSUE THREAD

**Issue by shamounni** [hut/ranger#495]
Hi,
I had a issue with the preview of picture on my urxvt terminal but now it's working and it's beautiful thank you very much. Here's a screenshot for the website : http://nongnu.org/ranger/screenshots.html

http://imgur.com/ou0ODd8

**Comment by hut** [comment]
Added, thanks^^ It will be synced in a couple of hours or something

**Comment by vevais** [comment]
Hey, can you tell me how you managed to get urxvt, transparency and antialiased fonts to work together with the image-preview? You don't seem to use a compositor but rather urxvt's transparency. Thanks in advance!
