### ISSUE TITLE
Viewing .gif files with w3mimgdisplay is unreliable

### ISSUE THREAD

**Issue by Zekario** [hut/ranger#496]
Most of the time I try to view a .gif in `ranger` with `w3m`, nothing happens for a second. Then, at the bottom in red, it says: `('Failed to execute w3mimgdisplay', [])`. Is this an issue with `w3m` or is it fixable in `ranger`? 

Rarely, I can view .gif files. If they are animated, it shows the first frame (which I'm fine with).

**Comment by jrcharney** [comment]
I've found success in using [sxiv](https://github.com/muennich/sxiv) for viewing gifs.  Getting them to animate in `rifle` is another story.

In your `~/.config/ranger/rc.conf` file, do you have a line that says `set preview_images true`?

Also if anyone knows how to help me with my situation to get `sxiv -a` to work in the `rifle` image preview, that would be great.

**Comment by hut** [comment]
Viewing images with w3mimgdisplay is unreliable, period. Not much we can do

**Comment by jrcharney** [comment]
Well, thanks anyway.
