### ISSUE TITLE
Queue rename after move

### ISSUE THREAD

**Issue by nonamethanks** [hut/ranger#513]
Hello, I tried searching the wiki, manpage and google but found no help.

Is there any way to queue a rename task so that it's done only after a move/copy process has ended? 
I often deal with large folders via SSH and I've found myself several times in need to rename the starting folder or change the end folder name, and this is obviously not possible while copy/move is doing its job. 
To wait for the job to complete is not an option either because it often takes hours and I don't have constant access to SSH to said server. 

Do I have to write my own functions for each of those two cases, or is there an easier way to do this that is not documented?

**Comment by hut** [comment]
Gotta write your own function, sorry. Should be straight-forward, ask away if you have trouble writing it.
