### ISSUE TITLE
No action found with custom rifle.conf

### ISSUE THREAD

**Issue by ranranking** [hut/ranger#516]
I could not open files if I have a `rifle.conf` in my `~/.config/ranger`. If I don't have this file, everything is fine. The file looks like:
``` bash
ext avi = mpv --no-border "$@"
ext mkv = mpv --no-border "$@"
ext rmvb = mpv --no-border "$@"
```
I can open the file types listed above, while the other file types can not be opened.

It seems that as long as I have the `rifle.conf` file in the `~/.config/ranger/` directory, even if it is blank, the default rifle.conf is not working. I will have to specify the opening method for each file type, or it will show `no action found`, and can not be opened.

I have homebrew version of ranger, OSX 10.11.4, iTerm2.9

**Comment by arkhan** [comment]
try this

#--------------------------------------------
# Audio without X
#-------------------------------------------
mime ^audio|ogg$, terminal, has mplayer  = mplayer -- "$@"
mime ^audio|ogg$, terminal, has mplayer2 = mplayer2 -- "$@"
mime ^audio|ogg$, terminal, has mpv      = mpv -- "$@"
ext midi?,        terminal, has wildmidi = wildmidi -- "$@"

#--------------------------------------------
# Video/Audio with a GUI
#-------------------------------------------
mime ^video|audio, has gmplayer, X, flag f = gmplayer -- "$@"
mime ^video|audio, has smplayer, X, flag f = smplayer "$@"
mime ^video,       has mpv,      X, flag f = mpv -- "$@"   
mime ^video,       has mpv,      X, flag f = mpv --fs -- "$@"
mime ^video,       has mplayer2, X, flag f = mplayer2 -- "$@"
mime ^video,       has mplayer2, X, flag f = mplayer2 -fs -- "$@"
mime ^video,       has mplayer,  X, flag f = mplayer -- "$@"  
mime ^video,       has mplayer,  X, flag f = mplayer -fs -- "$@"
mime ^video|audio, has vlc,      X, flag f = vlc -- "$@"
mime ^video|audio, has totem,    X, flag f = totem -- "$@"
mime ^video|audio, has totem,    X, flag f = totem --fullscreen -- "$@"

**Comment by ranranking** [comment]
No, still not working. As long as I have the `rifle.conf` file, I have there would be `No Action Found` unless I specify the opening method for each file.

**Comment by hut** [comment]
You have to specify every handler in your rifle.conf. This is because order matters.
