### ISSUE TITLE
New look

### ISSUE THREAD

**Issue by gineadai** [hut/ranger#518]
Probably Is it yet incomplete, but it now not usable. How can i bring old look back?

**Comment by gineadai** [comment]
it's just one column now instead of three on full screen and blue color just highlights lines with directories/files, not whole screen.

**Comment by hut** [comment]
Closed because april fools is over.

Here was the announcement FYI: http://lists.nongnu.org/archive/html/ranger-users/2016-04/msg00000.html

**Comment by alphapapa** [comment]
Did you accidentally run `deer`?

...Oh...as I was typing that, hut's comment appeared...uh...good joke?  :|

**Comment by alphapapa** [comment]
Wait... @hut... did you actually push that to master so that MELPA built it and people who upgraded today installed it?  D:

**Comment by alphapapa** [comment]
haha, okay, fail on my part, this is ranger not ranger.el (which I also keep an eye on).

Still...bold move, man, bold move.  LOL  :)
