### ISSUE TITLE
Search in Preview pane

### ISSUE THREAD

**Issue by nagakiran** [hut/ranger#519]
Is it possible to search for text in preview pane, just like we search for file names in other panes?
While previewing text files, want to quickly jump to content in preview matching a pattern. But as search is not allowed, had to open in a editor to search.

It will be very helpful if it can be done with out opening in an editor. Any workarounds for this?

**Comment by hut** [comment]
Currently this is not possible. It was already suggested in #312, so I'm closing this. `:map x shell less %f` opens the file in a pager with a search function, which might serve as a transitional workaround.
