### ISSUE TITLE
Displaying mtime in linemode requires subclassing?

### ISSUE THREAD

**Issue by alphapapa** [hut/ranger#520]
Hi,

Forgive me if this is a dupe, but I couldn't find any.

Am I correct in understanding that to display the mtime in the file list (`ls -l`-style) requires subclassing the LinemodeBase class?

If so, may I suggest that this be done and added as a built-in option?  It's good that we can sort by mtime, but sometimes it's necessary to see the actual mtimes.  Like right now, I am clearing out some old temp files, and I need to see the mtimes so I know which ones are old.

Thanks.

**Comment by Vifon** [comment]
Take a look if my patch does what you want.

**Comment by alphapapa** [comment]
@Vifon Thanks for putting that together.  I added another `sizemtime` line mode and rebased onto master: https://github.com/hut/ranger/issues/523
