### ISSUE TITLE
Is there a config setting to tell a specific directory to sort in reverse?

### ISSUE THREAD

**Issue by krompus** [hut/ranger#524]
I have this: `setlocal path=~/scrot$ sort basename` in my `rc.conf`. I'd simply like to tell that directory to sort in reverse, so that the newest files are at the top (I merged two screenshot directories, and now ctime doesn't work properly, but the titles are all formatted with the date first).

I know that I can type `orgg`, but it would be nice if the dir was sorted like this by default. :)

**Comment by hut** [comment]
`set` as well as `setlocal` can change any setting, not only "sort". I'm confident that with this information you  can figure out the solution yourself.

**Comment by krompus** [comment]
Oh, whelp.

    setlocal path=~/scrot$ sort basename
    setlocal path=~/scrot$ sort_reverse true

I was sure that I had tried that and that it didn't work. Works fine now. :P Thanks!
