### ISSUE TITLE
Actions.source() warning

### ISSUE THREAD

**Issue by Ale1ster** [hut/ranger#529]
When running ranger under PYTHONWARNINGS=module environment variable, it throws a ResourceWarning (namely that the configuration file is not closed) in actions.py:Actions.source().

This happens on release 1.7.2 (but a quick glance in the repo shows that nothing changed - at least in Actions.source()).

I don't know if or where anything else is needed, but the simplest fix would be to use

    with open(filename, 'r') as f:
        for line in f:

instead of

    for line in open(filename, 'r'):

**Comment by hut** [comment]
My impression was that it would be implicitly closed by the garbage collector, but let's not ignore the warnings. Thanks :)

**Comment by Ale1ster** [comment]
It is closed by the garbage collector, but the warnings are bothersome for people that have PYTHONWARNINGS enabled in their shell rc.
Thanks for the fix :)
