### ISSUE TITLE
Map keybinding to move by words on the command line

### ISSUE THREAD

**Issue by infokiller** [hut/ranger#530]
Is it possible to do something like:
```
cmap <C-left> eval fm.ui.console.move_word(left=1)
```

**Comment by infokiller** [comment]
Just noticed that this is a duplicate of #473 . @hut, should this one be closed?

**Comment by hut** [comment]
Yes, also I just implemented it: 33abb9feca7ff5fde9afebba744a575436d71656
Until this gets into stable, you'll need to use ranger's git version to use this change though.
