### ISSUE TITLE
Use GNU Source-highlight as an alternative to highlight

### ISSUE THREAD

**Issue by letientai299** [hut/ranger#534]
I have following lines in my `zshrc`, which add syntax coloring to less.
```zsh
GNU_SOURCE_HIGHLIGHT="/usr/bin/source-highlight-esc.sh"
export LESSOPEN="| $GNU_SOURCE_HIGHLIGHT %s"
export LESS='--tabs=4 --no-init --LONG-PROMPT --ignore-case --quit-if-one-screen --RAW-CONTROL-CHARS'
```
In ranger, those options are ignored.

**Comment by hut** [comment]
Why would ranger read less-specific environment variables? If you want to use your highlight script, take a look at `~/.config/ranger/scope.sh` (you can get it by typing `ranger --copy-config=scope`

**Comment by letientai299** [comment]
Thanks for the hint.
