### ISSUE TITLE
Filenames containing '²' cause range to show empty folders

### ISSUE THREAD

**Issue by nonamethanks** [hut/ranger#535]
As said in the title. Any directory which contains another directory or file with "²" or any other superscript character (³, etc) in their filename causes Ranger to not display anything inside it, and to return the error: 
`Invalid literal for int() with base 10: '²'`

To fix it I have to open a terminal and rename the file with mv.

**Comment by hut** [comment]
Wow. This is because "²".isdigit() is True in python3. Who would've thought.

Fixed, thanks.

**Comment by nonamethanks** [comment]
Wow, that was a quick one! Thanks a lot!
