### ISSUE TITLE
Navigating in lexicographical order

### ISSUE THREAD

**Issue by zunder** [hut/ranger#536]
I find it very confusing to use `find` in order to navigate through a long directory. Normally I remember the first letters of the file I am looking for, not the whole file's name. That is why lexicographical ordering is important in order to navigate. Let me give me an example:

I am having 3 files in my folder:
```
antirejection
satire
tire
```
Now I know that I am looking for something starting with a `ti` (tire in that example, but I do not know the word yet). So I press `f` and start typing `fi`. Obviously ranger would firstly go to antirejection, then hitting tab to satire and finally to tire.

What I would like to have is navigation based on **starts with** philosophy. If I type `ti`, I want to go to the first word starting with `ti`. Is this functionality already available in ranger?

**Comment by lamarpavel** [comment]
The `find` command is only an alias of the scout command, which has various
flags to change its behaviour. See `man ranger` for available options, I would
think that the `-l` flag is relevant to you as well as understanding patterns.

If you search for `^ti`, you will only find entries starting with `ti`.

**Comment by zunder** [comment]
`-l = letter skipping; e.g. allow "rdme" to match the file "readme"`

But I guess I could bind `:find ^` to a hotkey. Is there an easy way to define that in rc.conf?

**Comment by lamarpavel** [comment]
In your rc.conf:

`map f console find ^`

**Comment by zunder** [comment]
Works perfectly, thank you!
