### ISSUE TITLE
update image preview from command

### ISSUE THREAD

**Issue by fphammerle** [hut/ranger#538]
I added a command to rotate images.
How may I refresh the preview column in order to show the rotated version?

**Comment by hut** [comment]
Maybe `<Ctrl-R>`?

**Comment by fphammerle** [comment]
when pressing <Ctrl-R> the first element in the current directory is selected.
thanks for the tip!

**Comment by hut** [comment]
It resets ranger's caches. I'm not sure if it also refreshes preview images. Did it help?

**Comment by fphammerle** [comment]
Yes, when I reselect the image file after pressing Ctrl-R the rotated image
is being shown.
Reselecting the image (e.g. by selecting the file above <K> and going back
down <J>) also refreshes the preview image.
Initially I thought of using this behaviour to update the preview
but I was wondering whether a clean solution without de and reselecting the
file exists

On Fri, 6 May 2016 at 22:05 hut <notifications@github.com> wrote:

> It resets ranger's caches. I'm not sure if it also refreshes preview
> images. Did it help?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hut/ranger/issues/538#issuecomment-217545141>
>
-- 
Fabian Peter Hammerle

tel: +43 676 41 28 235
mail: fabian.hammerle@gmail.com

**Comment by hut** [comment]
Oh. Maybe `Ctrl+L` works?

**Comment by fphammerle** [comment]
Ctrl+L  refreshes the preview without changing the selection.
Perfect! Thank you!
