### ISSUE TITLE
autoupdate_cumulative_size is being ignored

### ISSUE THREAD

**Issue by duckdalbe** [hut/ranger#540]
Apparently setting `autoupdate_cumulative_size` doesn't have any effect, neither set in the config-file nor by typing `zu`.

Calculating sizes by `dc` (or `vdcv`) works well, but it's cumbersome to do that in each directory I'm navigating to.

**Comment by hut** [comment]
`autoupdate_cumulative_size` updates changes in directory size after you activated it with `dc`. Showing cumulative sizes for all files by default is not supported atm ;(

**Comment by duckdalbe** [comment]
Thanks for clarifying!

**Comment by c02y** [comment]
According to my test, like @duckdalbe said, the **autoupdate_cumulative_size** really does nothing, whether set it to **true** or **false**, the size of the highlighted directories wouldn't be displayed unless  executing **dc** command.

According to the man page of **autoupdate_cumulative_size**:

    autoupdate_cumulative_size [bool]
           You can display the "real" cumulative size of directories by using the command
           :get_cumulative_size or typing "dc".  The size is expensive to calculate and 
           will not be updated automatically. You can choose to update it automatically 
           though by turning on this option.

So would you tell me, what is the meaning of **autoupdate_cumulative_size** and how can I test the effect of it?
