### ISSUE TITLE
Using w3m-img can lead to broken pipes on exit

### ISSUE THREAD

**Issue by duganchen** [hut/ranger#548]
I've found that if I have video thumbnails on and I rapidly scroll through a directory full of video files, then exit Ranger, Ranger will periodically crash on exit ("q" key) with the following traceback:

    Traceback (most recent call last):
    File "/usr/bin/ranger", line 39, in <module>
    sys.exit(ranger.main())
    File "/usr/lib64/python2.7/site-packages/ranger/core/main.py", line 156, in main
    fm.ui.destroy()
    File "/usr/lib64/python2.7/site-packages/ranger/gui/ui.py", line 139, in destroy
    DisplayableContainer.destroy(self)
    File "/usr/lib64/python2.7/site-packages/ranger/gui/displayable.py", line 280, in destroy
    displayable.destroy()
    File "/usr/lib64/python2.7/site-packages/ranger/gui/widgets/pager.py", line 54, in destroy
    self.clear_image(force=True)
    File "/usr/lib64/python2.7/site-packages/ranger/gui/widgets/pager.py", line 42, in clear_image
    self.fm.image_displayer.clear(self.x, self.y, self.wid, self.hei)
    File "/usr/lib64/python2.7/site-packages/ranger/ext/img_display.py", line 120, in clear
    self.process.stdin.write(cmd)
    IOError: [Errno 32] Broken pipe

My terminal is xterm, in case you're wondering.

The result of this crash is the screen not being cleaned up. The ranger UI remains on the screen after exit, and my text cursor is gone.

**Comment by mrogalski** [comment]
I can't reproduce it.  Please provide more details, like:
Ranger version?  I see You are using python2.7 version, does the same thing happen on python3.4 version?
How many video files do You need to scroll through?
Are the file sizes relevant -- does this happen on small files or large files? 
Does the crash require any specific file?  Does the crash occur at a copy of a directory?  Could You run scope.sh on all the files in Your directory and check if there are any errors?  For instance, by running `for i in * ; do ~/.config/ranger/scope.sh $i 100 100 ~/.cache/ranger/$i ; done` in a **copy** of the directory that exhibits the problem?

**Comment by duganchen** [comment]
The ranger version was yesterday's master branch. Number of video files to scroll through? The range would be "several dozen". The files are large (dozens to hundreds of megabytes).

I wasn't able to make a copy of the directory yet, and that for loop didn't show errors (I redirected the output to a log).

I haven't been able to test a copy of the directory yet. Were you thinking that a hardware or filesystem error might be involved?

**Comment by mrogalski** [comment]
Hm, I tried it both on larger files than that and thousands (of copies) of smaller files, and couldn't reproduce the bug.  I thought that the problem might have been in a situation where ffmpegthumbnailer couldn't write the thumbnail to cache for some reason -- hardware error, video file error, You exit before the thumbnail is generated, or something like that.  If ranger works on a copy of a directory and not in the directory itself then the problem is somehow connected with that particular directory -- which might have pointed us to some kind of explanation.  Anyway, the patch should resolve that particular situation, whatever it might have been.
