### ISSUE TITLE
"S" (capital s) causes Ranger to crash

### ISSUE THREAD

**Issue by Zekario** [hut/ranger#555]
In `ranger` 1.7.2.1-1 on Arch Linux, pressing "S" while in `ranger` causes it to crash/close with no error message.

**Comment by hut** [comment]
Are you sure? "S" opens a shell for you which may be misinterpreted as a crash without error message. Do you return to ranger if you exit the shell?

**Comment by Zekario** [comment]
@hut It appears that is what is happening. Thanks!
