### ISSUE TITLE
last modified time for the main column

### ISSUE THREAD

**Issue by rbn42** [hut/ranger#557]
When I browse files with a graphical file manger like nautilus, I normally use a detailed list view, that can show the last modified time of a file.
Could you please add a display_mtime_in_main_column option to ranger?
I did some dirty hacking and it works fine.https://github.com/rbn42/ranger/commit/561c10922a9e4d87e9d5e42258d200791d867626

Thank you.

**Comment by mrogalski** [comment]
In the recent git versions of ranger there is a linemode for that.
Try `:linemode mtime` or `:linemode sizemtime`.

**Comment by rbn42** [comment]
Thank you

**Comment by hut** [comment]
And if you haven't seen them, there are key bindings starting with `M` for changing the line mode

**Comment by uqs** [comment]
It only shows HH:MM, any way to get it to show HH:MM:SS?

seems to be hardcoded here: https://github.com/ranger/ranger/blob/7e38143eaa91c82bed8f309aa167b1e6f2607576/ranger/core/linemode.py#L122

**Comment by toonn** [comment]
That could be a feature request.

**Comment by uqs** [comment]
Probably overkill though, I read up on the plugins a bit and I've simply put a new linemode plugin in ~/.config/ranger/plugins

```
from __future__ import (absolute_import, division, print_function)
from datetime import datetime
import ranger.api
from ranger.core.linemode import LinemodeBase

@ranger.api.register_linemode
class MtimeSecondsLinemode(LinemodeBase):
    name = "mtime_seconds"

    def filetitle(self, fobj, metadata):
        return fobj.relative_path

    def infostring(self, fobj, metadata):
        if fobj.stat is None:
            return '?'
        return datetime.fromtimestamp(fobj.stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S")
```

And overrode the mapping to that one: `map Mm linemode mtime_seconds`
