### ISSUE TITLE
How to set emacsclient as default editor?

### ISSUE THREAD

**Issue by ReneFroger** [hut/ranger#569]
I'm aware that I'm currently in the Lion's den, but I dare to ask the question.

I use Emacs with the Evil keybindings. So I would like to change the default editor from Vim to Emacs.

In my `rifle.conf` I have the following setting:

      flag f  = xdg-open "$1" 
     EDITOR='emacsclient -nw'
     DEFAULT_EDITOR = 'emacsclient -nw'

But unfortunately, it's not working. Any suggestions?

**Comment by hut** [comment]
These links will probably tell you everything you need to know about this:

https://github.com/hut/ranger/wiki/Common-Changes
https://github.com/hut/ranger/blob/master/examples/rifle_different_file_opener.conf

keep in mind that you can just directly replace `"$EDITOR"` in rifle.conf with `emacsclient -nw` if all else fails.

**Comment by Vifon** [comment]
I will only add that until recently rifle used `"$EDITOR"` instead of `$EDITOR`. Notice the quotes: it prevented the usage of multi-word commands. You may still have the old rifle rule.

**Comment by ReneFroger** [comment]
Thanks for your prompt replies, @hut and @Vifon  

     ext jpg = eog "$@"                                                                                                                                                                             
     ext cpp = emacsclient -nw "$@"                                                                                                                                                                 
     xdg-open "$1"                                                                                                                                                                                  
    "$EDITOR"=emacsclient -nw '$@'                                                                                                                                                                 
    EDITOR=emacsclient -nw '$@'                                                                                                                                                                    
    DEFAULT_EDITOR =emacsclient -nw '$@'                                                                                                                                                           
                                                          
It seems to work with .cpp files for example, but with other text files, Ranger is still not knowing what to do. Another suggestion?

**Comment by towc** [comment]
if anyone was trying to do this for vim (couldn't manage to make it work on the files I needed before doing this), all they need is to put

```
label editor = vim "$@"
label pager  = "$PAGER" -- "$@"
```

at the top of their `rifle.conf`

**Comment by Xunius** [comment]
seriously, why it is not defaulted to vim in the 1st place?

**Comment by toonn** [comment]
@Xunius vim is in fact a default baked into ranger, not sure what you're going on about. I'd also like to point out that everyone setting EDITOR is technically doing it wrong : p, you should set VISUAL instead.

**Comment by toonn** [comment]
@towc What files were these? Unless VISUAL or EDITOR are set, ranger defaults to vim.

**Comment by towc** [comment]
@toonn it was a long time ago. I think I was trying to open some html files with vim, but ranger was using the browser

**Comment by toonn** [comment]
A more correct solution would've been to add html to the ext's for your editor rule. Just opening everything with vim is hardly sane : )

**Comment by towc** [comment]
@toonn I'm going to need to remind you that your viewes are highly opinionated.

In my scenario, I'd prefer to open everything with vim, and just in case I didn't want to, to use `:open_with`. I didn't want to deal with every case in which I didn't want things to be opened in vim.

I really don't appreciate your tone here, regardless of your contributions to the tool, which are appreciated

**Comment by toonn** [comment]
My tone? Adding a rule for vim without "--" included just opens yourself up to gotchas. Your comments are read by other users who may not know as much as you, therefore the safest solution is the "more correct" one.

That being said, vim's a text editor so opening binary files with it is never a proper solution imo, your opinion may differ. You claim it's reasonable for everyone to just set a catchall rule opening vim, imo that's not reasonable and no one should do this even if they "don't want to deal with it properly."
I recommend not ascribing any "tone" to my comments at all, we'll both be happier for it.
