### ISSUE TITLE
play video with mplayer without X11

### ISSUE THREAD

**Issue by raoofha** [hut/ranger#92]
hi thank u for your great job on ranger 

I have a problem play video file with mplayer in console without any X window 
when I open video file from ranger it works fine and play video but shortcut for mplayer
do not work

I wonder is it possible to some how overcome this problem 

thank you

**Comment by hut** [comment]
I'm closing this because of old age and inactivity. If this is still an issue, feel free to reopen it.

**Comment by OliverLew** [comment]
Maybe add some parameters in the rifle.conf:
```
mime ^video, terminal, !X, has mpv       = mpv --vo=gpu --gpu-context=drm -- "$@"
mime ^video, terminal, !X, has mplayer   = mplayer -vo fbdev2 -- "$@"
```
